
#include "Time.idl"

module cali_msgs{
    module msg{
        struct Header{
            uint16 message_id;
            uint16 length;
            uint32 protocol_id;
            proj233_msgs::msg::Time stamp;
        };
    };
};