// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TimeTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.2.0).
 */

#include "TimeTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "Time.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace common_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Time_type_identifier(
        TypeIdentifierPair& type_ids_Time)
{

    ReturnCode_t return_code_Time {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Time =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "common_msgs::msg::dds_::Time_", type_ids_Time);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Time)
    {
        StructTypeFlag struct_flags_Time = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_Time = "common_msgs::msg::dds_::Time_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Time;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Time;
        CompleteTypeDetail detail_Time = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Time, ann_custom_Time, type_name_Time.to_string());
        CompleteStructHeader header_Time;
        header_Time = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Time);
        CompleteStructMemberSeq member_seq_Time;
        {
            TypeIdentifierPair type_ids_sec;
            ReturnCode_t return_code_sec {eprosima::fastdds::dds::RETCODE_OK};
            return_code_sec =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_sec);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_sec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "sec Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_sec = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_sec = 0x00000000;
            bool common_sec_ec {false};
            CommonStructMember common_sec {TypeObjectUtils::build_common_struct_member(member_id_sec, member_flags_sec, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_sec, common_sec_ec))};
            if (!common_sec_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure sec member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_sec = "sec";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_sec;
            ann_custom_Time.reset();
            CompleteMemberDetail detail_sec = TypeObjectUtils::build_complete_member_detail(name_sec, member_ann_builtin_sec, ann_custom_Time);
            CompleteStructMember member_sec = TypeObjectUtils::build_complete_struct_member(common_sec, detail_sec);
            TypeObjectUtils::add_complete_struct_member(member_seq_Time, member_sec);
        }
        {
            TypeIdentifierPair type_ids_nanosec;
            ReturnCode_t return_code_nanosec {eprosima::fastdds::dds::RETCODE_OK};
            return_code_nanosec =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_nanosec);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_nanosec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "nanosec Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_nanosec = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_nanosec = 0x00000001;
            bool common_nanosec_ec {false};
            CommonStructMember common_nanosec {TypeObjectUtils::build_common_struct_member(member_id_nanosec, member_flags_nanosec, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_nanosec, common_nanosec_ec))};
            if (!common_nanosec_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure nanosec member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_nanosec = "nanosec";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_nanosec;
            ann_custom_Time.reset();
            CompleteMemberDetail detail_nanosec = TypeObjectUtils::build_complete_member_detail(name_nanosec, member_ann_builtin_nanosec, ann_custom_Time);
            CompleteStructMember member_nanosec = TypeObjectUtils::build_complete_struct_member(common_nanosec, detail_nanosec);
            TypeObjectUtils::add_complete_struct_member(member_seq_Time, member_nanosec);
        }
        CompleteStructType struct_type_Time = TypeObjectUtils::build_complete_struct_type(struct_flags_Time, header_Time, member_seq_Time);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Time, type_name_Time.to_string(), type_ids_Time))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "common_msgs::msg::Time already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace msg

} // namespace common_msgs

