// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Time.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.2.0).
 */

#ifndef FAST_DDS_GENERATED__COMMON_MSGS_MSG_TIME_HPP
#define FAST_DDS_GENERATED__COMMON_MSGS_MSG_TIME_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TIME_SOURCE)
#define TIME_DllAPI __declspec( dllexport )
#else
#define TIME_DllAPI __declspec( dllimport )
#endif // TIME_SOURCE
#else
#define TIME_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TIME_DllAPI
#endif // _WIN32

namespace common_msgs {

namespace msg {

/*!
 * @brief This class represents the structure Time defined by the user in the IDL file.
 * @ingroup Time
 */
class Time
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Time()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Time()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Time that will be copied.
     */
    eProsima_user_DllExport Time(
            const Time& x)
    {
                    m_sec = x.m_sec;

                    m_nanosec = x.m_nanosec;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Time that will be copied.
     */
    eProsima_user_DllExport Time(
            Time&& x) noexcept
    {
        m_sec = x.m_sec;
        m_nanosec = x.m_nanosec;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Time that will be copied.
     */
    eProsima_user_DllExport Time& operator =(
            const Time& x)
    {

                    m_sec = x.m_sec;

                    m_nanosec = x.m_nanosec;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Time that will be copied.
     */
    eProsima_user_DllExport Time& operator =(
            Time&& x) noexcept
    {

        m_sec = x.m_sec;
        m_nanosec = x.m_nanosec;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Time object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Time& x) const
    {
        return (m_sec == x.m_sec &&
           m_nanosec == x.m_nanosec);
    }

    /*!
     * @brief Comparison operator.
     * @param x Time object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Time& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member sec
     * @param _sec New value for member sec
     */
    eProsima_user_DllExport void sec(
            int32_t _sec)
    {
        m_sec = _sec;
    }

    /*!
     * @brief This function returns the value of member sec
     * @return Value of member sec
     */
    eProsima_user_DllExport int32_t sec() const
    {
        return m_sec;
    }

    /*!
     * @brief This function returns a reference to member sec
     * @return Reference to member sec
     */
    eProsima_user_DllExport int32_t& sec()
    {
        return m_sec;
    }


    /*!
     * @brief This function sets a value in member nanosec
     * @param _nanosec New value for member nanosec
     */
    eProsima_user_DllExport void nanosec(
            uint32_t _nanosec)
    {
        m_nanosec = _nanosec;
    }

    /*!
     * @brief This function returns the value of member nanosec
     * @return Value of member nanosec
     */
    eProsima_user_DllExport uint32_t nanosec() const
    {
        return m_nanosec;
    }

    /*!
     * @brief This function returns a reference to member nanosec
     * @return Reference to member nanosec
     */
    eProsima_user_DllExport uint32_t& nanosec()
    {
        return m_nanosec;
    }



private:

    int32_t m_sec{0};
    uint32_t m_nanosec{0};

};

} // namespace msg

} // namespace common_msgs

#endif // _FAST_DDS_GENERATED_COMMON_MSGS_MSG_TIME_HPP_


