// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ACCEgoVehCmdHeaderTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.2.0).
 */

#include "ACCEgoVehCmdHeaderTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "ACCEgoVehCmdHeader.hpp"

#include "Time.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace std_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_ACCEgoVehCmdHeader_type_identifier(
        TypeIdentifierPair& type_ids_ACCEgoVehCmdHeader)
{

    ReturnCode_t return_code_ACCEgoVehCmdHeader {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ACCEgoVehCmdHeader =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "std_msgs::msg::dds_::ACCEgoVehCmdHeader_", type_ids_ACCEgoVehCmdHeader);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ACCEgoVehCmdHeader)
    {
        StructTypeFlag struct_flags_ACCEgoVehCmdHeader = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_ACCEgoVehCmdHeader = "std_msgs::msg::dds_::ACCEgoVehCmdHeader_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ACCEgoVehCmdHeader;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ACCEgoVehCmdHeader;
        CompleteTypeDetail detail_ACCEgoVehCmdHeader = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ACCEgoVehCmdHeader, ann_custom_ACCEgoVehCmdHeader, type_name_ACCEgoVehCmdHeader.to_string());
        CompleteStructHeader header_ACCEgoVehCmdHeader;
        header_ACCEgoVehCmdHeader = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_ACCEgoVehCmdHeader);
        CompleteStructMemberSeq member_seq_ACCEgoVehCmdHeader;
        {
            TypeIdentifierPair type_ids_stamp;
            ReturnCode_t return_code_stamp {eprosima::fastdds::dds::RETCODE_OK};
            return_code_stamp =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "common_msgs::msg::dds_::Time_", type_ids_stamp);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_stamp)
            {
                ::common_msgs::msg::register_Time_type_identifier(type_ids_stamp);
            }
            StructMemberFlag member_flags_stamp = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_stamp = 0x00000000;
            bool common_stamp_ec {false};
            CommonStructMember common_stamp {TypeObjectUtils::build_common_struct_member(member_id_stamp, member_flags_stamp, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_stamp, common_stamp_ec))};
            if (!common_stamp_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure stamp member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_stamp = "stamp";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_stamp;
            ann_custom_ACCEgoVehCmdHeader.reset();
            CompleteMemberDetail detail_stamp = TypeObjectUtils::build_complete_member_detail(name_stamp, member_ann_builtin_stamp, ann_custom_ACCEgoVehCmdHeader);
            CompleteStructMember member_stamp = TypeObjectUtils::build_complete_struct_member(common_stamp, detail_stamp);
            TypeObjectUtils::add_complete_struct_member(member_seq_ACCEgoVehCmdHeader, member_stamp);
        }
        {
            TypeIdentifierPair type_ids_frame_id;
            ReturnCode_t return_code_frame_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_frame_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_frame_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_frame_id)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_frame_id))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_frame_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_frame_id = 0x00000001;
            bool common_frame_id_ec {false};
            CommonStructMember common_frame_id {TypeObjectUtils::build_common_struct_member(member_id_frame_id, member_flags_frame_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_frame_id, common_frame_id_ec))};
            if (!common_frame_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure frame_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_frame_id = "frame_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_frame_id;
            ann_custom_ACCEgoVehCmdHeader.reset();
            CompleteMemberDetail detail_frame_id = TypeObjectUtils::build_complete_member_detail(name_frame_id, member_ann_builtin_frame_id, ann_custom_ACCEgoVehCmdHeader);
            CompleteStructMember member_frame_id = TypeObjectUtils::build_complete_struct_member(common_frame_id, detail_frame_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_ACCEgoVehCmdHeader, member_frame_id);
        }
        CompleteStructType struct_type_ACCEgoVehCmdHeader = TypeObjectUtils::build_complete_struct_type(struct_flags_ACCEgoVehCmdHeader, header_ACCEgoVehCmdHeader, member_seq_ACCEgoVehCmdHeader);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_ACCEgoVehCmdHeader, type_name_ACCEgoVehCmdHeader.to_string(), type_ids_ACCEgoVehCmdHeader))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "std_msgs::msg::ACCEgoVehCmdHeader already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace msg

} // namespace std_msgs

