// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BodyCommand.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.2.0).
 */

#ifndef FAST_DDS_GENERATED__CONTROL_MSGS_MSG_BODYCOMMAND_HPP
#define FAST_DDS_GENERATED__CONTROL_MSGS_MSG_BODYCOMMAND_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(BODYCOMMAND_SOURCE)
#define BODYCOMMAND_DllAPI __declspec( dllexport )
#else
#define BODYCOMMAND_DllAPI __declspec( dllimport )
#endif // BODYCOMMAND_SOURCE
#else
#define BODYCOMMAND_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define BODYCOMMAND_DllAPI
#endif // _WIN32

namespace control_msgs {

namespace msg {

/*!
 * @brief This class represents the structure BodyCommand defined by the user in the IDL file.
 * @ingroup BodyCommand
 */
class BodyCommand
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport BodyCommand()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~BodyCommand()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object BodyCommand that will be copied.
     */
    eProsima_user_DllExport BodyCommand(
            const BodyCommand& x)
    {
                    m_turn_light_cmd = x.m_turn_light_cmd;

                    m_fog_light_cmd = x.m_fog_light_cmd;

                    m_brake_light_cmd = x.m_brake_light_cmd;

                    m_hazard_light_cmd = x.m_hazard_light_cmd;

                    m_reverse_light_cmd = x.m_reverse_light_cmd;

                    m_horn_cmd = x.m_horn_cmd;

                    m_high_beam_light_cmd = x.m_high_beam_light_cmd;

                    m_low_beam_light_cmd = x.m_low_beam_light_cmd;

                    m_day_time_run_light_cmd = x.m_day_time_run_light_cmd;

                    m_wind_shield_wash_cmd = x.m_wind_shield_wash_cmd;

                    m_front_wiper_cmd = x.m_front_wiper_cmd;

                    m_rear_wiper_cmd = x.m_rear_wiper_cmd;

                    m_left_front_window_cmd = x.m_left_front_window_cmd;

                    m_right_front_window_cmd = x.m_right_front_window_cmd;

                    m_left_rear_window_cmd = x.m_left_rear_window_cmd;

                    m_right_rear_window_cmd = x.m_right_rear_window_cmd;

                    m_door_lock_cmd = x.m_door_lock_cmd;

                    m_fcw_display_cmd = x.m_fcw_display_cmd;

                    m_aeb_display_cmd = x.m_aeb_display_cmd;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object BodyCommand that will be copied.
     */
    eProsima_user_DllExport BodyCommand(
            BodyCommand&& x) noexcept
    {
        m_turn_light_cmd = x.m_turn_light_cmd;
        m_fog_light_cmd = x.m_fog_light_cmd;
        m_brake_light_cmd = x.m_brake_light_cmd;
        m_hazard_light_cmd = x.m_hazard_light_cmd;
        m_reverse_light_cmd = x.m_reverse_light_cmd;
        m_horn_cmd = x.m_horn_cmd;
        m_high_beam_light_cmd = x.m_high_beam_light_cmd;
        m_low_beam_light_cmd = x.m_low_beam_light_cmd;
        m_day_time_run_light_cmd = x.m_day_time_run_light_cmd;
        m_wind_shield_wash_cmd = x.m_wind_shield_wash_cmd;
        m_front_wiper_cmd = x.m_front_wiper_cmd;
        m_rear_wiper_cmd = x.m_rear_wiper_cmd;
        m_left_front_window_cmd = x.m_left_front_window_cmd;
        m_right_front_window_cmd = x.m_right_front_window_cmd;
        m_left_rear_window_cmd = x.m_left_rear_window_cmd;
        m_right_rear_window_cmd = x.m_right_rear_window_cmd;
        m_door_lock_cmd = x.m_door_lock_cmd;
        m_fcw_display_cmd = x.m_fcw_display_cmd;
        m_aeb_display_cmd = x.m_aeb_display_cmd;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object BodyCommand that will be copied.
     */
    eProsima_user_DllExport BodyCommand& operator =(
            const BodyCommand& x)
    {

                    m_turn_light_cmd = x.m_turn_light_cmd;

                    m_fog_light_cmd = x.m_fog_light_cmd;

                    m_brake_light_cmd = x.m_brake_light_cmd;

                    m_hazard_light_cmd = x.m_hazard_light_cmd;

                    m_reverse_light_cmd = x.m_reverse_light_cmd;

                    m_horn_cmd = x.m_horn_cmd;

                    m_high_beam_light_cmd = x.m_high_beam_light_cmd;

                    m_low_beam_light_cmd = x.m_low_beam_light_cmd;

                    m_day_time_run_light_cmd = x.m_day_time_run_light_cmd;

                    m_wind_shield_wash_cmd = x.m_wind_shield_wash_cmd;

                    m_front_wiper_cmd = x.m_front_wiper_cmd;

                    m_rear_wiper_cmd = x.m_rear_wiper_cmd;

                    m_left_front_window_cmd = x.m_left_front_window_cmd;

                    m_right_front_window_cmd = x.m_right_front_window_cmd;

                    m_left_rear_window_cmd = x.m_left_rear_window_cmd;

                    m_right_rear_window_cmd = x.m_right_rear_window_cmd;

                    m_door_lock_cmd = x.m_door_lock_cmd;

                    m_fcw_display_cmd = x.m_fcw_display_cmd;

                    m_aeb_display_cmd = x.m_aeb_display_cmd;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object BodyCommand that will be copied.
     */
    eProsima_user_DllExport BodyCommand& operator =(
            BodyCommand&& x) noexcept
    {

        m_turn_light_cmd = x.m_turn_light_cmd;
        m_fog_light_cmd = x.m_fog_light_cmd;
        m_brake_light_cmd = x.m_brake_light_cmd;
        m_hazard_light_cmd = x.m_hazard_light_cmd;
        m_reverse_light_cmd = x.m_reverse_light_cmd;
        m_horn_cmd = x.m_horn_cmd;
        m_high_beam_light_cmd = x.m_high_beam_light_cmd;
        m_low_beam_light_cmd = x.m_low_beam_light_cmd;
        m_day_time_run_light_cmd = x.m_day_time_run_light_cmd;
        m_wind_shield_wash_cmd = x.m_wind_shield_wash_cmd;
        m_front_wiper_cmd = x.m_front_wiper_cmd;
        m_rear_wiper_cmd = x.m_rear_wiper_cmd;
        m_left_front_window_cmd = x.m_left_front_window_cmd;
        m_right_front_window_cmd = x.m_right_front_window_cmd;
        m_left_rear_window_cmd = x.m_left_rear_window_cmd;
        m_right_rear_window_cmd = x.m_right_rear_window_cmd;
        m_door_lock_cmd = x.m_door_lock_cmd;
        m_fcw_display_cmd = x.m_fcw_display_cmd;
        m_aeb_display_cmd = x.m_aeb_display_cmd;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x BodyCommand object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const BodyCommand& x) const
    {
        return (m_turn_light_cmd == x.m_turn_light_cmd &&
           m_fog_light_cmd == x.m_fog_light_cmd &&
           m_brake_light_cmd == x.m_brake_light_cmd &&
           m_hazard_light_cmd == x.m_hazard_light_cmd &&
           m_reverse_light_cmd == x.m_reverse_light_cmd &&
           m_horn_cmd == x.m_horn_cmd &&
           m_high_beam_light_cmd == x.m_high_beam_light_cmd &&
           m_low_beam_light_cmd == x.m_low_beam_light_cmd &&
           m_day_time_run_light_cmd == x.m_day_time_run_light_cmd &&
           m_wind_shield_wash_cmd == x.m_wind_shield_wash_cmd &&
           m_front_wiper_cmd == x.m_front_wiper_cmd &&
           m_rear_wiper_cmd == x.m_rear_wiper_cmd &&
           m_left_front_window_cmd == x.m_left_front_window_cmd &&
           m_right_front_window_cmd == x.m_right_front_window_cmd &&
           m_left_rear_window_cmd == x.m_left_rear_window_cmd &&
           m_right_rear_window_cmd == x.m_right_rear_window_cmd &&
           m_door_lock_cmd == x.m_door_lock_cmd &&
           m_fcw_display_cmd == x.m_fcw_display_cmd &&
           m_aeb_display_cmd == x.m_aeb_display_cmd);
    }

    /*!
     * @brief Comparison operator.
     * @param x BodyCommand object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const BodyCommand& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member turn_light_cmd
     * @param _turn_light_cmd New value for member turn_light_cmd
     */
    eProsima_user_DllExport void turn_light_cmd(
            int8_t _turn_light_cmd)
    {
        m_turn_light_cmd = _turn_light_cmd;
    }

    /*!
     * @brief This function returns the value of member turn_light_cmd
     * @return Value of member turn_light_cmd
     */
    eProsima_user_DllExport int8_t turn_light_cmd() const
    {
        return m_turn_light_cmd;
    }

    /*!
     * @brief This function returns a reference to member turn_light_cmd
     * @return Reference to member turn_light_cmd
     */
    eProsima_user_DllExport int8_t& turn_light_cmd()
    {
        return m_turn_light_cmd;
    }


    /*!
     * @brief This function sets a value in member fog_light_cmd
     * @param _fog_light_cmd New value for member fog_light_cmd
     */
    eProsima_user_DllExport void fog_light_cmd(
            int8_t _fog_light_cmd)
    {
        m_fog_light_cmd = _fog_light_cmd;
    }

    /*!
     * @brief This function returns the value of member fog_light_cmd
     * @return Value of member fog_light_cmd
     */
    eProsima_user_DllExport int8_t fog_light_cmd() const
    {
        return m_fog_light_cmd;
    }

    /*!
     * @brief This function returns a reference to member fog_light_cmd
     * @return Reference to member fog_light_cmd
     */
    eProsima_user_DllExport int8_t& fog_light_cmd()
    {
        return m_fog_light_cmd;
    }


    /*!
     * @brief This function sets a value in member brake_light_cmd
     * @param _brake_light_cmd New value for member brake_light_cmd
     */
    eProsima_user_DllExport void brake_light_cmd(
            bool _brake_light_cmd)
    {
        m_brake_light_cmd = _brake_light_cmd;
    }

    /*!
     * @brief This function returns the value of member brake_light_cmd
     * @return Value of member brake_light_cmd
     */
    eProsima_user_DllExport bool brake_light_cmd() const
    {
        return m_brake_light_cmd;
    }

    /*!
     * @brief This function returns a reference to member brake_light_cmd
     * @return Reference to member brake_light_cmd
     */
    eProsima_user_DllExport bool& brake_light_cmd()
    {
        return m_brake_light_cmd;
    }


    /*!
     * @brief This function sets a value in member hazard_light_cmd
     * @param _hazard_light_cmd New value for member hazard_light_cmd
     */
    eProsima_user_DllExport void hazard_light_cmd(
            bool _hazard_light_cmd)
    {
        m_hazard_light_cmd = _hazard_light_cmd;
    }

    /*!
     * @brief This function returns the value of member hazard_light_cmd
     * @return Value of member hazard_light_cmd
     */
    eProsima_user_DllExport bool hazard_light_cmd() const
    {
        return m_hazard_light_cmd;
    }

    /*!
     * @brief This function returns a reference to member hazard_light_cmd
     * @return Reference to member hazard_light_cmd
     */
    eProsima_user_DllExport bool& hazard_light_cmd()
    {
        return m_hazard_light_cmd;
    }


    /*!
     * @brief This function sets a value in member reverse_light_cmd
     * @param _reverse_light_cmd New value for member reverse_light_cmd
     */
    eProsima_user_DllExport void reverse_light_cmd(
            bool _reverse_light_cmd)
    {
        m_reverse_light_cmd = _reverse_light_cmd;
    }

    /*!
     * @brief This function returns the value of member reverse_light_cmd
     * @return Value of member reverse_light_cmd
     */
    eProsima_user_DllExport bool reverse_light_cmd() const
    {
        return m_reverse_light_cmd;
    }

    /*!
     * @brief This function returns a reference to member reverse_light_cmd
     * @return Reference to member reverse_light_cmd
     */
    eProsima_user_DllExport bool& reverse_light_cmd()
    {
        return m_reverse_light_cmd;
    }


    /*!
     * @brief This function sets a value in member horn_cmd
     * @param _horn_cmd New value for member horn_cmd
     */
    eProsima_user_DllExport void horn_cmd(
            bool _horn_cmd)
    {
        m_horn_cmd = _horn_cmd;
    }

    /*!
     * @brief This function returns the value of member horn_cmd
     * @return Value of member horn_cmd
     */
    eProsima_user_DllExport bool horn_cmd() const
    {
        return m_horn_cmd;
    }

    /*!
     * @brief This function returns a reference to member horn_cmd
     * @return Reference to member horn_cmd
     */
    eProsima_user_DllExport bool& horn_cmd()
    {
        return m_horn_cmd;
    }


    /*!
     * @brief This function sets a value in member high_beam_light_cmd
     * @param _high_beam_light_cmd New value for member high_beam_light_cmd
     */
    eProsima_user_DllExport void high_beam_light_cmd(
            int8_t _high_beam_light_cmd)
    {
        m_high_beam_light_cmd = _high_beam_light_cmd;
    }

    /*!
     * @brief This function returns the value of member high_beam_light_cmd
     * @return Value of member high_beam_light_cmd
     */
    eProsima_user_DllExport int8_t high_beam_light_cmd() const
    {
        return m_high_beam_light_cmd;
    }

    /*!
     * @brief This function returns a reference to member high_beam_light_cmd
     * @return Reference to member high_beam_light_cmd
     */
    eProsima_user_DllExport int8_t& high_beam_light_cmd()
    {
        return m_high_beam_light_cmd;
    }


    /*!
     * @brief This function sets a value in member low_beam_light_cmd
     * @param _low_beam_light_cmd New value for member low_beam_light_cmd
     */
    eProsima_user_DllExport void low_beam_light_cmd(
            bool _low_beam_light_cmd)
    {
        m_low_beam_light_cmd = _low_beam_light_cmd;
    }

    /*!
     * @brief This function returns the value of member low_beam_light_cmd
     * @return Value of member low_beam_light_cmd
     */
    eProsima_user_DllExport bool low_beam_light_cmd() const
    {
        return m_low_beam_light_cmd;
    }

    /*!
     * @brief This function returns a reference to member low_beam_light_cmd
     * @return Reference to member low_beam_light_cmd
     */
    eProsima_user_DllExport bool& low_beam_light_cmd()
    {
        return m_low_beam_light_cmd;
    }


    /*!
     * @brief This function sets a value in member day_time_run_light_cmd
     * @param _day_time_run_light_cmd New value for member day_time_run_light_cmd
     */
    eProsima_user_DllExport void day_time_run_light_cmd(
            bool _day_time_run_light_cmd)
    {
        m_day_time_run_light_cmd = _day_time_run_light_cmd;
    }

    /*!
     * @brief This function returns the value of member day_time_run_light_cmd
     * @return Value of member day_time_run_light_cmd
     */
    eProsima_user_DllExport bool day_time_run_light_cmd() const
    {
        return m_day_time_run_light_cmd;
    }

    /*!
     * @brief This function returns a reference to member day_time_run_light_cmd
     * @return Reference to member day_time_run_light_cmd
     */
    eProsima_user_DllExport bool& day_time_run_light_cmd()
    {
        return m_day_time_run_light_cmd;
    }


    /*!
     * @brief This function sets a value in member wind_shield_wash_cmd
     * @param _wind_shield_wash_cmd New value for member wind_shield_wash_cmd
     */
    eProsima_user_DllExport void wind_shield_wash_cmd(
            bool _wind_shield_wash_cmd)
    {
        m_wind_shield_wash_cmd = _wind_shield_wash_cmd;
    }

    /*!
     * @brief This function returns the value of member wind_shield_wash_cmd
     * @return Value of member wind_shield_wash_cmd
     */
    eProsima_user_DllExport bool wind_shield_wash_cmd() const
    {
        return m_wind_shield_wash_cmd;
    }

    /*!
     * @brief This function returns a reference to member wind_shield_wash_cmd
     * @return Reference to member wind_shield_wash_cmd
     */
    eProsima_user_DllExport bool& wind_shield_wash_cmd()
    {
        return m_wind_shield_wash_cmd;
    }


    /*!
     * @brief This function sets a value in member front_wiper_cmd
     * @param _front_wiper_cmd New value for member front_wiper_cmd
     */
    eProsima_user_DllExport void front_wiper_cmd(
            int8_t _front_wiper_cmd)
    {
        m_front_wiper_cmd = _front_wiper_cmd;
    }

    /*!
     * @brief This function returns the value of member front_wiper_cmd
     * @return Value of member front_wiper_cmd
     */
    eProsima_user_DllExport int8_t front_wiper_cmd() const
    {
        return m_front_wiper_cmd;
    }

    /*!
     * @brief This function returns a reference to member front_wiper_cmd
     * @return Reference to member front_wiper_cmd
     */
    eProsima_user_DllExport int8_t& front_wiper_cmd()
    {
        return m_front_wiper_cmd;
    }


    /*!
     * @brief This function sets a value in member rear_wiper_cmd
     * @param _rear_wiper_cmd New value for member rear_wiper_cmd
     */
    eProsima_user_DllExport void rear_wiper_cmd(
            int8_t _rear_wiper_cmd)
    {
        m_rear_wiper_cmd = _rear_wiper_cmd;
    }

    /*!
     * @brief This function returns the value of member rear_wiper_cmd
     * @return Value of member rear_wiper_cmd
     */
    eProsima_user_DllExport int8_t rear_wiper_cmd() const
    {
        return m_rear_wiper_cmd;
    }

    /*!
     * @brief This function returns a reference to member rear_wiper_cmd
     * @return Reference to member rear_wiper_cmd
     */
    eProsima_user_DllExport int8_t& rear_wiper_cmd()
    {
        return m_rear_wiper_cmd;
    }


    /*!
     * @brief This function sets a value in member left_front_window_cmd
     * @param _left_front_window_cmd New value for member left_front_window_cmd
     */
    eProsima_user_DllExport void left_front_window_cmd(
            int8_t _left_front_window_cmd)
    {
        m_left_front_window_cmd = _left_front_window_cmd;
    }

    /*!
     * @brief This function returns the value of member left_front_window_cmd
     * @return Value of member left_front_window_cmd
     */
    eProsima_user_DllExport int8_t left_front_window_cmd() const
    {
        return m_left_front_window_cmd;
    }

    /*!
     * @brief This function returns a reference to member left_front_window_cmd
     * @return Reference to member left_front_window_cmd
     */
    eProsima_user_DllExport int8_t& left_front_window_cmd()
    {
        return m_left_front_window_cmd;
    }


    /*!
     * @brief This function sets a value in member right_front_window_cmd
     * @param _right_front_window_cmd New value for member right_front_window_cmd
     */
    eProsima_user_DllExport void right_front_window_cmd(
            int8_t _right_front_window_cmd)
    {
        m_right_front_window_cmd = _right_front_window_cmd;
    }

    /*!
     * @brief This function returns the value of member right_front_window_cmd
     * @return Value of member right_front_window_cmd
     */
    eProsima_user_DllExport int8_t right_front_window_cmd() const
    {
        return m_right_front_window_cmd;
    }

    /*!
     * @brief This function returns a reference to member right_front_window_cmd
     * @return Reference to member right_front_window_cmd
     */
    eProsima_user_DllExport int8_t& right_front_window_cmd()
    {
        return m_right_front_window_cmd;
    }


    /*!
     * @brief This function sets a value in member left_rear_window_cmd
     * @param _left_rear_window_cmd New value for member left_rear_window_cmd
     */
    eProsima_user_DllExport void left_rear_window_cmd(
            int8_t _left_rear_window_cmd)
    {
        m_left_rear_window_cmd = _left_rear_window_cmd;
    }

    /*!
     * @brief This function returns the value of member left_rear_window_cmd
     * @return Value of member left_rear_window_cmd
     */
    eProsima_user_DllExport int8_t left_rear_window_cmd() const
    {
        return m_left_rear_window_cmd;
    }

    /*!
     * @brief This function returns a reference to member left_rear_window_cmd
     * @return Reference to member left_rear_window_cmd
     */
    eProsima_user_DllExport int8_t& left_rear_window_cmd()
    {
        return m_left_rear_window_cmd;
    }


    /*!
     * @brief This function sets a value in member right_rear_window_cmd
     * @param _right_rear_window_cmd New value for member right_rear_window_cmd
     */
    eProsima_user_DllExport void right_rear_window_cmd(
            int8_t _right_rear_window_cmd)
    {
        m_right_rear_window_cmd = _right_rear_window_cmd;
    }

    /*!
     * @brief This function returns the value of member right_rear_window_cmd
     * @return Value of member right_rear_window_cmd
     */
    eProsima_user_DllExport int8_t right_rear_window_cmd() const
    {
        return m_right_rear_window_cmd;
    }

    /*!
     * @brief This function returns a reference to member right_rear_window_cmd
     * @return Reference to member right_rear_window_cmd
     */
    eProsima_user_DllExport int8_t& right_rear_window_cmd()
    {
        return m_right_rear_window_cmd;
    }


    /*!
     * @brief This function sets a value in member door_lock_cmd
     * @param _door_lock_cmd New value for member door_lock_cmd
     */
    eProsima_user_DllExport void door_lock_cmd(
            int8_t _door_lock_cmd)
    {
        m_door_lock_cmd = _door_lock_cmd;
    }

    /*!
     * @brief This function returns the value of member door_lock_cmd
     * @return Value of member door_lock_cmd
     */
    eProsima_user_DllExport int8_t door_lock_cmd() const
    {
        return m_door_lock_cmd;
    }

    /*!
     * @brief This function returns a reference to member door_lock_cmd
     * @return Reference to member door_lock_cmd
     */
    eProsima_user_DllExport int8_t& door_lock_cmd()
    {
        return m_door_lock_cmd;
    }


    /*!
     * @brief This function sets a value in member fcw_display_cmd
     * @param _fcw_display_cmd New value for member fcw_display_cmd
     */
    eProsima_user_DllExport void fcw_display_cmd(
            int8_t _fcw_display_cmd)
    {
        m_fcw_display_cmd = _fcw_display_cmd;
    }

    /*!
     * @brief This function returns the value of member fcw_display_cmd
     * @return Value of member fcw_display_cmd
     */
    eProsima_user_DllExport int8_t fcw_display_cmd() const
    {
        return m_fcw_display_cmd;
    }

    /*!
     * @brief This function returns a reference to member fcw_display_cmd
     * @return Reference to member fcw_display_cmd
     */
    eProsima_user_DllExport int8_t& fcw_display_cmd()
    {
        return m_fcw_display_cmd;
    }


    /*!
     * @brief This function sets a value in member aeb_display_cmd
     * @param _aeb_display_cmd New value for member aeb_display_cmd
     */
    eProsima_user_DllExport void aeb_display_cmd(
            int8_t _aeb_display_cmd)
    {
        m_aeb_display_cmd = _aeb_display_cmd;
    }

    /*!
     * @brief This function returns the value of member aeb_display_cmd
     * @return Value of member aeb_display_cmd
     */
    eProsima_user_DllExport int8_t aeb_display_cmd() const
    {
        return m_aeb_display_cmd;
    }

    /*!
     * @brief This function returns a reference to member aeb_display_cmd
     * @return Reference to member aeb_display_cmd
     */
    eProsima_user_DllExport int8_t& aeb_display_cmd()
    {
        return m_aeb_display_cmd;
    }



private:

    int8_t m_turn_light_cmd{0};
    int8_t m_fog_light_cmd{0};
    bool m_brake_light_cmd{false};
    bool m_hazard_light_cmd{false};
    bool m_reverse_light_cmd{false};
    bool m_horn_cmd{false};
    int8_t m_high_beam_light_cmd{0};
    bool m_low_beam_light_cmd{false};
    bool m_day_time_run_light_cmd{false};
    bool m_wind_shield_wash_cmd{false};
    int8_t m_front_wiper_cmd{0};
    int8_t m_rear_wiper_cmd{0};
    int8_t m_left_front_window_cmd{0};
    int8_t m_right_front_window_cmd{0};
    int8_t m_left_rear_window_cmd{0};
    int8_t m_right_rear_window_cmd{0};
    int8_t m_door_lock_cmd{0};
    int8_t m_fcw_display_cmd{0};
    int8_t m_aeb_display_cmd{0};

};

} // namespace msg

} // namespace control_msgs

#endif // _FAST_DDS_GENERATED_CONTROL_MSGS_MSG_BODYCOMMAND_HPP_


