// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BodyCommandCdrAux.ipp
 * This source file contains some declarations of CDR related functions.
 *
 * This file was generated by the tool fastddsgen (version: 4.2.0).
 */

#ifndef FAST_DDS_GENERATED__CONTROL_MSGS_MSG_BODYCOMMANDCDRAUX_IPP
#define FAST_DDS_GENERATED__CONTROL_MSGS_MSG_BODYCOMMANDCDRAUX_IPP

#include "BodyCommandCdrAux.hpp"

#include <fastcdr/Cdr.h>
#include <fastcdr/CdrSizeCalculator.hpp>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

namespace eprosima {
namespace fastcdr {

template<>
eProsima_user_DllExport size_t calculate_serialized_size(
        eprosima::fastcdr::CdrSizeCalculator& calculator,
        const control_msgs::msg::BodyCommand& data,
        size_t& current_alignment)
{
    using namespace control_msgs::msg;

    static_cast<void>(data);

    eprosima::fastcdr::EncodingAlgorithmFlag previous_encoding = calculator.get_encoding();
    size_t calculated_size {calculator.begin_calculate_type_serialized_size(
                                eprosima::fastcdr::CdrVersion::XCDRv2 == calculator.get_cdr_version() ?
                                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2 :
                                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR,
                                current_alignment)};


        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(0),
                data.turn_light_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(1),
                data.fog_light_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(2),
                data.brake_light_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(3),
                data.hazard_light_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(4),
                data.reverse_light_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(5),
                data.horn_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(6),
                data.high_beam_light_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(7),
                data.low_beam_light_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(8),
                data.day_time_run_light_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(9),
                data.wind_shield_wash_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(10),
                data.front_wiper_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(11),
                data.rear_wiper_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(12),
                data.left_front_window_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(13),
                data.right_front_window_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(14),
                data.left_rear_window_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(15),
                data.right_rear_window_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(16),
                data.door_lock_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(17),
                data.fcw_display_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(18),
                data.aeb_display_cmd(), current_alignment);


    calculated_size += calculator.end_calculate_type_serialized_size(previous_encoding, current_alignment);

    return calculated_size;
}

template<>
eProsima_user_DllExport void serialize(
        eprosima::fastcdr::Cdr& scdr,
        const control_msgs::msg::BodyCommand& data)
{
    using namespace control_msgs::msg;

    eprosima::fastcdr::Cdr::state current_state(scdr);
    scdr.begin_serialize_type(current_state,
            eprosima::fastcdr::CdrVersion::XCDRv2 == scdr.get_cdr_version() ?
            eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2 :
            eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR);

    scdr
        << eprosima::fastcdr::MemberId(0) << data.turn_light_cmd()
        << eprosima::fastcdr::MemberId(1) << data.fog_light_cmd()
        << eprosima::fastcdr::MemberId(2) << data.brake_light_cmd()
        << eprosima::fastcdr::MemberId(3) << data.hazard_light_cmd()
        << eprosima::fastcdr::MemberId(4) << data.reverse_light_cmd()
        << eprosima::fastcdr::MemberId(5) << data.horn_cmd()
        << eprosima::fastcdr::MemberId(6) << data.high_beam_light_cmd()
        << eprosima::fastcdr::MemberId(7) << data.low_beam_light_cmd()
        << eprosima::fastcdr::MemberId(8) << data.day_time_run_light_cmd()
        << eprosima::fastcdr::MemberId(9) << data.wind_shield_wash_cmd()
        << eprosima::fastcdr::MemberId(10) << data.front_wiper_cmd()
        << eprosima::fastcdr::MemberId(11) << data.rear_wiper_cmd()
        << eprosima::fastcdr::MemberId(12) << data.left_front_window_cmd()
        << eprosima::fastcdr::MemberId(13) << data.right_front_window_cmd()
        << eprosima::fastcdr::MemberId(14) << data.left_rear_window_cmd()
        << eprosima::fastcdr::MemberId(15) << data.right_rear_window_cmd()
        << eprosima::fastcdr::MemberId(16) << data.door_lock_cmd()
        << eprosima::fastcdr::MemberId(17) << data.fcw_display_cmd()
        << eprosima::fastcdr::MemberId(18) << data.aeb_display_cmd()
;
    scdr.end_serialize_type(current_state);
}

template<>
eProsima_user_DllExport void deserialize(
        eprosima::fastcdr::Cdr& cdr,
        control_msgs::msg::BodyCommand& data)
{
    using namespace control_msgs::msg;

    cdr.deserialize_type(eprosima::fastcdr::CdrVersion::XCDRv2 == cdr.get_cdr_version() ?
            eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2 :
            eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR,
            [&data](eprosima::fastcdr::Cdr& dcdr, const eprosima::fastcdr::MemberId& mid) -> bool
            {
                bool ret_value = true;
                switch (mid.id)
                {
                                        case 0:
                                                dcdr >> data.turn_light_cmd();
                                            break;

                                        case 1:
                                                dcdr >> data.fog_light_cmd();
                                            break;

                                        case 2:
                                                dcdr >> data.brake_light_cmd();
                                            break;

                                        case 3:
                                                dcdr >> data.hazard_light_cmd();
                                            break;

                                        case 4:
                                                dcdr >> data.reverse_light_cmd();
                                            break;

                                        case 5:
                                                dcdr >> data.horn_cmd();
                                            break;

                                        case 6:
                                                dcdr >> data.high_beam_light_cmd();
                                            break;

                                        case 7:
                                                dcdr >> data.low_beam_light_cmd();
                                            break;

                                        case 8:
                                                dcdr >> data.day_time_run_light_cmd();
                                            break;

                                        case 9:
                                                dcdr >> data.wind_shield_wash_cmd();
                                            break;

                                        case 10:
                                                dcdr >> data.front_wiper_cmd();
                                            break;

                                        case 11:
                                                dcdr >> data.rear_wiper_cmd();
                                            break;

                                        case 12:
                                                dcdr >> data.left_front_window_cmd();
                                            break;

                                        case 13:
                                                dcdr >> data.right_front_window_cmd();
                                            break;

                                        case 14:
                                                dcdr >> data.left_rear_window_cmd();
                                            break;

                                        case 15:
                                                dcdr >> data.right_rear_window_cmd();
                                            break;

                                        case 16:
                                                dcdr >> data.door_lock_cmd();
                                            break;

                                        case 17:
                                                dcdr >> data.fcw_display_cmd();
                                            break;

                                        case 18:
                                                dcdr >> data.aeb_display_cmd();
                                            break;

                    default:
                        ret_value = false;
                        break;
                }
                return ret_value;
            });
}

void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const control_msgs::msg::BodyCommand& data)
{
    using namespace control_msgs::msg;

    static_cast<void>(scdr);
    static_cast<void>(data);
                        scdr << data.turn_light_cmd();

                        scdr << data.fog_light_cmd();

                        scdr << data.brake_light_cmd();

                        scdr << data.hazard_light_cmd();

                        scdr << data.reverse_light_cmd();

                        scdr << data.horn_cmd();

                        scdr << data.high_beam_light_cmd();

                        scdr << data.low_beam_light_cmd();

                        scdr << data.day_time_run_light_cmd();

                        scdr << data.wind_shield_wash_cmd();

                        scdr << data.front_wiper_cmd();

                        scdr << data.rear_wiper_cmd();

                        scdr << data.left_front_window_cmd();

                        scdr << data.right_front_window_cmd();

                        scdr << data.left_rear_window_cmd();

                        scdr << data.right_rear_window_cmd();

                        scdr << data.door_lock_cmd();

                        scdr << data.fcw_display_cmd();

                        scdr << data.aeb_display_cmd();

}



} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__CONTROL_MSGS_MSG_BODYCOMMANDCDRAUX_IPP

