// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BodyCommandTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.2.0).
 */

#include "BodyCommandTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "BodyCommand.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace control_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_BodyCommand_type_identifier(
        TypeIdentifierPair& type_ids_BodyCommand)
{

    ReturnCode_t return_code_BodyCommand {eprosima::fastdds::dds::RETCODE_OK};
    return_code_BodyCommand =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "control_msgs::msg::dds_::BodyCommand_", type_ids_BodyCommand);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_BodyCommand)
    {
        StructTypeFlag struct_flags_BodyCommand = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_BodyCommand = "control_msgs::msg::dds_::BodyCommand_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_BodyCommand;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_BodyCommand;
        CompleteTypeDetail detail_BodyCommand = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_BodyCommand, ann_custom_BodyCommand, type_name_BodyCommand.to_string());
        CompleteStructHeader header_BodyCommand;
        header_BodyCommand = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_BodyCommand);
        CompleteStructMemberSeq member_seq_BodyCommand;
        {
            TypeIdentifierPair type_ids_turn_light_cmd;
            ReturnCode_t return_code_turn_light_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_turn_light_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_turn_light_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_turn_light_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "turn_light_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_turn_light_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_turn_light_cmd = 0x00000000;
            bool common_turn_light_cmd_ec {false};
            CommonStructMember common_turn_light_cmd {TypeObjectUtils::build_common_struct_member(member_id_turn_light_cmd, member_flags_turn_light_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_turn_light_cmd, common_turn_light_cmd_ec))};
            if (!common_turn_light_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure turn_light_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_turn_light_cmd = "turn_light_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_turn_light_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_turn_light_cmd = TypeObjectUtils::build_complete_member_detail(name_turn_light_cmd, member_ann_builtin_turn_light_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_turn_light_cmd = TypeObjectUtils::build_complete_struct_member(common_turn_light_cmd, detail_turn_light_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_turn_light_cmd);
        }
        {
            TypeIdentifierPair type_ids_fog_light_cmd;
            ReturnCode_t return_code_fog_light_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_fog_light_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_fog_light_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_fog_light_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "fog_light_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_fog_light_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_fog_light_cmd = 0x00000001;
            bool common_fog_light_cmd_ec {false};
            CommonStructMember common_fog_light_cmd {TypeObjectUtils::build_common_struct_member(member_id_fog_light_cmd, member_flags_fog_light_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_fog_light_cmd, common_fog_light_cmd_ec))};
            if (!common_fog_light_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure fog_light_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_fog_light_cmd = "fog_light_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_fog_light_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_fog_light_cmd = TypeObjectUtils::build_complete_member_detail(name_fog_light_cmd, member_ann_builtin_fog_light_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_fog_light_cmd = TypeObjectUtils::build_complete_struct_member(common_fog_light_cmd, detail_fog_light_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_fog_light_cmd);
        }
        {
            TypeIdentifierPair type_ids_brake_light_cmd;
            ReturnCode_t return_code_brake_light_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_brake_light_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_brake_light_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_brake_light_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "brake_light_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_brake_light_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_brake_light_cmd = 0x00000002;
            bool common_brake_light_cmd_ec {false};
            CommonStructMember common_brake_light_cmd {TypeObjectUtils::build_common_struct_member(member_id_brake_light_cmd, member_flags_brake_light_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_brake_light_cmd, common_brake_light_cmd_ec))};
            if (!common_brake_light_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure brake_light_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_brake_light_cmd = "brake_light_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_brake_light_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_brake_light_cmd = TypeObjectUtils::build_complete_member_detail(name_brake_light_cmd, member_ann_builtin_brake_light_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_brake_light_cmd = TypeObjectUtils::build_complete_struct_member(common_brake_light_cmd, detail_brake_light_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_brake_light_cmd);
        }
        {
            TypeIdentifierPair type_ids_hazard_light_cmd;
            ReturnCode_t return_code_hazard_light_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_hazard_light_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_hazard_light_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_hazard_light_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "hazard_light_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_hazard_light_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_hazard_light_cmd = 0x00000003;
            bool common_hazard_light_cmd_ec {false};
            CommonStructMember common_hazard_light_cmd {TypeObjectUtils::build_common_struct_member(member_id_hazard_light_cmd, member_flags_hazard_light_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_hazard_light_cmd, common_hazard_light_cmd_ec))};
            if (!common_hazard_light_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure hazard_light_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_hazard_light_cmd = "hazard_light_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_hazard_light_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_hazard_light_cmd = TypeObjectUtils::build_complete_member_detail(name_hazard_light_cmd, member_ann_builtin_hazard_light_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_hazard_light_cmd = TypeObjectUtils::build_complete_struct_member(common_hazard_light_cmd, detail_hazard_light_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_hazard_light_cmd);
        }
        {
            TypeIdentifierPair type_ids_reverse_light_cmd;
            ReturnCode_t return_code_reverse_light_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_reverse_light_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_reverse_light_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_reverse_light_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "reverse_light_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_reverse_light_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_reverse_light_cmd = 0x00000004;
            bool common_reverse_light_cmd_ec {false};
            CommonStructMember common_reverse_light_cmd {TypeObjectUtils::build_common_struct_member(member_id_reverse_light_cmd, member_flags_reverse_light_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_reverse_light_cmd, common_reverse_light_cmd_ec))};
            if (!common_reverse_light_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure reverse_light_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_reverse_light_cmd = "reverse_light_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_reverse_light_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_reverse_light_cmd = TypeObjectUtils::build_complete_member_detail(name_reverse_light_cmd, member_ann_builtin_reverse_light_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_reverse_light_cmd = TypeObjectUtils::build_complete_struct_member(common_reverse_light_cmd, detail_reverse_light_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_reverse_light_cmd);
        }
        {
            TypeIdentifierPair type_ids_horn_cmd;
            ReturnCode_t return_code_horn_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_horn_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_horn_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_horn_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "horn_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_horn_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_horn_cmd = 0x00000005;
            bool common_horn_cmd_ec {false};
            CommonStructMember common_horn_cmd {TypeObjectUtils::build_common_struct_member(member_id_horn_cmd, member_flags_horn_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_horn_cmd, common_horn_cmd_ec))};
            if (!common_horn_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure horn_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_horn_cmd = "horn_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_horn_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_horn_cmd = TypeObjectUtils::build_complete_member_detail(name_horn_cmd, member_ann_builtin_horn_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_horn_cmd = TypeObjectUtils::build_complete_struct_member(common_horn_cmd, detail_horn_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_horn_cmd);
        }
        {
            TypeIdentifierPair type_ids_high_beam_light_cmd;
            ReturnCode_t return_code_high_beam_light_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_high_beam_light_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_high_beam_light_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_high_beam_light_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "high_beam_light_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_high_beam_light_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_high_beam_light_cmd = 0x00000006;
            bool common_high_beam_light_cmd_ec {false};
            CommonStructMember common_high_beam_light_cmd {TypeObjectUtils::build_common_struct_member(member_id_high_beam_light_cmd, member_flags_high_beam_light_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_high_beam_light_cmd, common_high_beam_light_cmd_ec))};
            if (!common_high_beam_light_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure high_beam_light_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_high_beam_light_cmd = "high_beam_light_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_high_beam_light_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_high_beam_light_cmd = TypeObjectUtils::build_complete_member_detail(name_high_beam_light_cmd, member_ann_builtin_high_beam_light_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_high_beam_light_cmd = TypeObjectUtils::build_complete_struct_member(common_high_beam_light_cmd, detail_high_beam_light_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_high_beam_light_cmd);
        }
        {
            TypeIdentifierPair type_ids_low_beam_light_cmd;
            ReturnCode_t return_code_low_beam_light_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_low_beam_light_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_low_beam_light_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_low_beam_light_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "low_beam_light_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_low_beam_light_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_low_beam_light_cmd = 0x00000007;
            bool common_low_beam_light_cmd_ec {false};
            CommonStructMember common_low_beam_light_cmd {TypeObjectUtils::build_common_struct_member(member_id_low_beam_light_cmd, member_flags_low_beam_light_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_low_beam_light_cmd, common_low_beam_light_cmd_ec))};
            if (!common_low_beam_light_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure low_beam_light_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_low_beam_light_cmd = "low_beam_light_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_low_beam_light_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_low_beam_light_cmd = TypeObjectUtils::build_complete_member_detail(name_low_beam_light_cmd, member_ann_builtin_low_beam_light_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_low_beam_light_cmd = TypeObjectUtils::build_complete_struct_member(common_low_beam_light_cmd, detail_low_beam_light_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_low_beam_light_cmd);
        }
        {
            TypeIdentifierPair type_ids_day_time_run_light_cmd;
            ReturnCode_t return_code_day_time_run_light_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_day_time_run_light_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_day_time_run_light_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_day_time_run_light_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "day_time_run_light_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_day_time_run_light_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_day_time_run_light_cmd = 0x00000008;
            bool common_day_time_run_light_cmd_ec {false};
            CommonStructMember common_day_time_run_light_cmd {TypeObjectUtils::build_common_struct_member(member_id_day_time_run_light_cmd, member_flags_day_time_run_light_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_day_time_run_light_cmd, common_day_time_run_light_cmd_ec))};
            if (!common_day_time_run_light_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure day_time_run_light_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_day_time_run_light_cmd = "day_time_run_light_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_day_time_run_light_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_day_time_run_light_cmd = TypeObjectUtils::build_complete_member_detail(name_day_time_run_light_cmd, member_ann_builtin_day_time_run_light_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_day_time_run_light_cmd = TypeObjectUtils::build_complete_struct_member(common_day_time_run_light_cmd, detail_day_time_run_light_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_day_time_run_light_cmd);
        }
        {
            TypeIdentifierPair type_ids_wind_shield_wash_cmd;
            ReturnCode_t return_code_wind_shield_wash_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_wind_shield_wash_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_wind_shield_wash_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_wind_shield_wash_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "wind_shield_wash_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_wind_shield_wash_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_wind_shield_wash_cmd = 0x00000009;
            bool common_wind_shield_wash_cmd_ec {false};
            CommonStructMember common_wind_shield_wash_cmd {TypeObjectUtils::build_common_struct_member(member_id_wind_shield_wash_cmd, member_flags_wind_shield_wash_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_wind_shield_wash_cmd, common_wind_shield_wash_cmd_ec))};
            if (!common_wind_shield_wash_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure wind_shield_wash_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_wind_shield_wash_cmd = "wind_shield_wash_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_wind_shield_wash_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_wind_shield_wash_cmd = TypeObjectUtils::build_complete_member_detail(name_wind_shield_wash_cmd, member_ann_builtin_wind_shield_wash_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_wind_shield_wash_cmd = TypeObjectUtils::build_complete_struct_member(common_wind_shield_wash_cmd, detail_wind_shield_wash_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_wind_shield_wash_cmd);
        }
        {
            TypeIdentifierPair type_ids_front_wiper_cmd;
            ReturnCode_t return_code_front_wiper_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_front_wiper_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_front_wiper_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_front_wiper_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "front_wiper_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_front_wiper_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_front_wiper_cmd = 0x0000000a;
            bool common_front_wiper_cmd_ec {false};
            CommonStructMember common_front_wiper_cmd {TypeObjectUtils::build_common_struct_member(member_id_front_wiper_cmd, member_flags_front_wiper_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_front_wiper_cmd, common_front_wiper_cmd_ec))};
            if (!common_front_wiper_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure front_wiper_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_front_wiper_cmd = "front_wiper_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_front_wiper_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_front_wiper_cmd = TypeObjectUtils::build_complete_member_detail(name_front_wiper_cmd, member_ann_builtin_front_wiper_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_front_wiper_cmd = TypeObjectUtils::build_complete_struct_member(common_front_wiper_cmd, detail_front_wiper_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_front_wiper_cmd);
        }
        {
            TypeIdentifierPair type_ids_rear_wiper_cmd;
            ReturnCode_t return_code_rear_wiper_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_rear_wiper_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_rear_wiper_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_rear_wiper_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "rear_wiper_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_rear_wiper_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_rear_wiper_cmd = 0x0000000b;
            bool common_rear_wiper_cmd_ec {false};
            CommonStructMember common_rear_wiper_cmd {TypeObjectUtils::build_common_struct_member(member_id_rear_wiper_cmd, member_flags_rear_wiper_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_rear_wiper_cmd, common_rear_wiper_cmd_ec))};
            if (!common_rear_wiper_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure rear_wiper_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_rear_wiper_cmd = "rear_wiper_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_rear_wiper_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_rear_wiper_cmd = TypeObjectUtils::build_complete_member_detail(name_rear_wiper_cmd, member_ann_builtin_rear_wiper_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_rear_wiper_cmd = TypeObjectUtils::build_complete_struct_member(common_rear_wiper_cmd, detail_rear_wiper_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_rear_wiper_cmd);
        }
        {
            TypeIdentifierPair type_ids_left_front_window_cmd;
            ReturnCode_t return_code_left_front_window_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_left_front_window_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_left_front_window_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_left_front_window_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "left_front_window_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_left_front_window_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_left_front_window_cmd = 0x0000000c;
            bool common_left_front_window_cmd_ec {false};
            CommonStructMember common_left_front_window_cmd {TypeObjectUtils::build_common_struct_member(member_id_left_front_window_cmd, member_flags_left_front_window_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_left_front_window_cmd, common_left_front_window_cmd_ec))};
            if (!common_left_front_window_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure left_front_window_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_left_front_window_cmd = "left_front_window_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_left_front_window_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_left_front_window_cmd = TypeObjectUtils::build_complete_member_detail(name_left_front_window_cmd, member_ann_builtin_left_front_window_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_left_front_window_cmd = TypeObjectUtils::build_complete_struct_member(common_left_front_window_cmd, detail_left_front_window_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_left_front_window_cmd);
        }
        {
            TypeIdentifierPair type_ids_right_front_window_cmd;
            ReturnCode_t return_code_right_front_window_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_right_front_window_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_right_front_window_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_right_front_window_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "right_front_window_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_right_front_window_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_right_front_window_cmd = 0x0000000d;
            bool common_right_front_window_cmd_ec {false};
            CommonStructMember common_right_front_window_cmd {TypeObjectUtils::build_common_struct_member(member_id_right_front_window_cmd, member_flags_right_front_window_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_right_front_window_cmd, common_right_front_window_cmd_ec))};
            if (!common_right_front_window_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure right_front_window_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_right_front_window_cmd = "right_front_window_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_right_front_window_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_right_front_window_cmd = TypeObjectUtils::build_complete_member_detail(name_right_front_window_cmd, member_ann_builtin_right_front_window_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_right_front_window_cmd = TypeObjectUtils::build_complete_struct_member(common_right_front_window_cmd, detail_right_front_window_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_right_front_window_cmd);
        }
        {
            TypeIdentifierPair type_ids_left_rear_window_cmd;
            ReturnCode_t return_code_left_rear_window_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_left_rear_window_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_left_rear_window_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_left_rear_window_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "left_rear_window_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_left_rear_window_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_left_rear_window_cmd = 0x0000000e;
            bool common_left_rear_window_cmd_ec {false};
            CommonStructMember common_left_rear_window_cmd {TypeObjectUtils::build_common_struct_member(member_id_left_rear_window_cmd, member_flags_left_rear_window_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_left_rear_window_cmd, common_left_rear_window_cmd_ec))};
            if (!common_left_rear_window_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure left_rear_window_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_left_rear_window_cmd = "left_rear_window_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_left_rear_window_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_left_rear_window_cmd = TypeObjectUtils::build_complete_member_detail(name_left_rear_window_cmd, member_ann_builtin_left_rear_window_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_left_rear_window_cmd = TypeObjectUtils::build_complete_struct_member(common_left_rear_window_cmd, detail_left_rear_window_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_left_rear_window_cmd);
        }
        {
            TypeIdentifierPair type_ids_right_rear_window_cmd;
            ReturnCode_t return_code_right_rear_window_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_right_rear_window_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_right_rear_window_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_right_rear_window_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "right_rear_window_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_right_rear_window_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_right_rear_window_cmd = 0x0000000f;
            bool common_right_rear_window_cmd_ec {false};
            CommonStructMember common_right_rear_window_cmd {TypeObjectUtils::build_common_struct_member(member_id_right_rear_window_cmd, member_flags_right_rear_window_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_right_rear_window_cmd, common_right_rear_window_cmd_ec))};
            if (!common_right_rear_window_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure right_rear_window_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_right_rear_window_cmd = "right_rear_window_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_right_rear_window_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_right_rear_window_cmd = TypeObjectUtils::build_complete_member_detail(name_right_rear_window_cmd, member_ann_builtin_right_rear_window_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_right_rear_window_cmd = TypeObjectUtils::build_complete_struct_member(common_right_rear_window_cmd, detail_right_rear_window_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_right_rear_window_cmd);
        }
        {
            TypeIdentifierPair type_ids_door_lock_cmd;
            ReturnCode_t return_code_door_lock_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_door_lock_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_door_lock_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_door_lock_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "door_lock_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_door_lock_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_door_lock_cmd = 0x00000010;
            bool common_door_lock_cmd_ec {false};
            CommonStructMember common_door_lock_cmd {TypeObjectUtils::build_common_struct_member(member_id_door_lock_cmd, member_flags_door_lock_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_door_lock_cmd, common_door_lock_cmd_ec))};
            if (!common_door_lock_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure door_lock_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_door_lock_cmd = "door_lock_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_door_lock_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_door_lock_cmd = TypeObjectUtils::build_complete_member_detail(name_door_lock_cmd, member_ann_builtin_door_lock_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_door_lock_cmd = TypeObjectUtils::build_complete_struct_member(common_door_lock_cmd, detail_door_lock_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_door_lock_cmd);
        }
        {
            TypeIdentifierPair type_ids_fcw_display_cmd;
            ReturnCode_t return_code_fcw_display_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_fcw_display_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_fcw_display_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_fcw_display_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "fcw_display_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_fcw_display_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_fcw_display_cmd = 0x00000011;
            bool common_fcw_display_cmd_ec {false};
            CommonStructMember common_fcw_display_cmd {TypeObjectUtils::build_common_struct_member(member_id_fcw_display_cmd, member_flags_fcw_display_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_fcw_display_cmd, common_fcw_display_cmd_ec))};
            if (!common_fcw_display_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure fcw_display_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_fcw_display_cmd = "fcw_display_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_fcw_display_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_fcw_display_cmd = TypeObjectUtils::build_complete_member_detail(name_fcw_display_cmd, member_ann_builtin_fcw_display_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_fcw_display_cmd = TypeObjectUtils::build_complete_struct_member(common_fcw_display_cmd, detail_fcw_display_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_fcw_display_cmd);
        }
        {
            TypeIdentifierPair type_ids_aeb_display_cmd;
            ReturnCode_t return_code_aeb_display_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_aeb_display_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_aeb_display_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_aeb_display_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "aeb_display_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_aeb_display_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_aeb_display_cmd = 0x00000012;
            bool common_aeb_display_cmd_ec {false};
            CommonStructMember common_aeb_display_cmd {TypeObjectUtils::build_common_struct_member(member_id_aeb_display_cmd, member_flags_aeb_display_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_aeb_display_cmd, common_aeb_display_cmd_ec))};
            if (!common_aeb_display_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure aeb_display_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_aeb_display_cmd = "aeb_display_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_aeb_display_cmd;
            ann_custom_BodyCommand.reset();
            CompleteMemberDetail detail_aeb_display_cmd = TypeObjectUtils::build_complete_member_detail(name_aeb_display_cmd, member_ann_builtin_aeb_display_cmd, ann_custom_BodyCommand);
            CompleteStructMember member_aeb_display_cmd = TypeObjectUtils::build_complete_struct_member(common_aeb_display_cmd, detail_aeb_display_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_BodyCommand, member_aeb_display_cmd);
        }
        CompleteStructType struct_type_BodyCommand = TypeObjectUtils::build_complete_struct_type(struct_flags_BodyCommand, header_BodyCommand, member_seq_BodyCommand);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_BodyCommand, type_name_BodyCommand.to_string(), type_ids_BodyCommand))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "control_msgs::msg::BodyCommand already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace msg

} // namespace control_msgs

