// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ChassisCommand.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.2.0).
 */

#ifndef FAST_DDS_GENERATED__CONTROL_MSGS_MSG_CHASSISCOMMAND_HPP
#define FAST_DDS_GENERATED__CONTROL_MSGS_MSG_CHASSISCOMMAND_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CHASSISCOMMAND_SOURCE)
#define CHASSISCOMMAND_DllAPI __declspec( dllexport )
#else
#define CHASSISCOMMAND_DllAPI __declspec( dllimport )
#endif // CHASSISCOMMAND_SOURCE
#else
#define CHASSISCOMMAND_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CHASSISCOMMAND_DllAPI
#endif // _WIN32

namespace control_msgs {

namespace msg {

/*!
 * @brief This class represents the structure ChassisCommand defined by the user in the IDL file.
 * @ingroup ChassisCommand
 */
class ChassisCommand
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ChassisCommand()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ChassisCommand()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ChassisCommand that will be copied.
     */
    eProsima_user_DllExport ChassisCommand(
            const ChassisCommand& x)
    {
                    m_ads_function = x.m_ads_function;

                    m_steer_angle_cmd = x.m_steer_angle_cmd;

                    m_steer_wheel_torque_cmd = x.m_steer_wheel_torque_cmd;

                    m_steer_vibration_cmd = x.m_steer_vibration_cmd;

                    m_long_acceleration_cmd = x.m_long_acceleration_cmd;

                    m_long_accelerationjerk_max = x.m_long_accelerationjerk_max;

                    m_long_accelerationjerk_min = x.m_long_accelerationjerk_min;

                    m_gear_cmd = x.m_gear_cmd;

                    m_aeb_acceleration_cmd = x.m_aeb_acceleration_cmd;

                    m_aeb_acceleration_enable = x.m_aeb_acceleration_enable;

                    m_aeb_aba_request = x.m_aeb_aba_request;

                    m_aeb_aba_level = x.m_aeb_aba_level;

                    m_aeb_jerk_req = x.m_aeb_jerk_req;

                    m_aeb_jerk_level = x.m_aeb_jerk_level;

                    m_aeb_prefill_req = x.m_aeb_prefill_req;

                    m_eba_decel_req = x.m_eba_decel_req;

                    m_aeb_hold_req = x.m_aeb_hold_req;

                    m_brake_pedal_cmd = x.m_brake_pedal_cmd;

                    m_brake_pedal_cmd_enable = x.m_brake_pedal_cmd_enable;

                    m_accelration_pedal_cmd = x.m_accelration_pedal_cmd;

                    m_accelration_pedal_cmd_enble = x.m_accelration_pedal_cmd_enble;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ChassisCommand that will be copied.
     */
    eProsima_user_DllExport ChassisCommand(
            ChassisCommand&& x) noexcept
    {
        m_ads_function = x.m_ads_function;
        m_steer_angle_cmd = x.m_steer_angle_cmd;
        m_steer_wheel_torque_cmd = x.m_steer_wheel_torque_cmd;
        m_steer_vibration_cmd = x.m_steer_vibration_cmd;
        m_long_acceleration_cmd = x.m_long_acceleration_cmd;
        m_long_accelerationjerk_max = x.m_long_accelerationjerk_max;
        m_long_accelerationjerk_min = x.m_long_accelerationjerk_min;
        m_gear_cmd = x.m_gear_cmd;
        m_aeb_acceleration_cmd = x.m_aeb_acceleration_cmd;
        m_aeb_acceleration_enable = x.m_aeb_acceleration_enable;
        m_aeb_aba_request = x.m_aeb_aba_request;
        m_aeb_aba_level = x.m_aeb_aba_level;
        m_aeb_jerk_req = x.m_aeb_jerk_req;
        m_aeb_jerk_level = x.m_aeb_jerk_level;
        m_aeb_prefill_req = x.m_aeb_prefill_req;
        m_eba_decel_req = x.m_eba_decel_req;
        m_aeb_hold_req = x.m_aeb_hold_req;
        m_brake_pedal_cmd = x.m_brake_pedal_cmd;
        m_brake_pedal_cmd_enable = x.m_brake_pedal_cmd_enable;
        m_accelration_pedal_cmd = x.m_accelration_pedal_cmd;
        m_accelration_pedal_cmd_enble = x.m_accelration_pedal_cmd_enble;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ChassisCommand that will be copied.
     */
    eProsima_user_DllExport ChassisCommand& operator =(
            const ChassisCommand& x)
    {

                    m_ads_function = x.m_ads_function;

                    m_steer_angle_cmd = x.m_steer_angle_cmd;

                    m_steer_wheel_torque_cmd = x.m_steer_wheel_torque_cmd;

                    m_steer_vibration_cmd = x.m_steer_vibration_cmd;

                    m_long_acceleration_cmd = x.m_long_acceleration_cmd;

                    m_long_accelerationjerk_max = x.m_long_accelerationjerk_max;

                    m_long_accelerationjerk_min = x.m_long_accelerationjerk_min;

                    m_gear_cmd = x.m_gear_cmd;

                    m_aeb_acceleration_cmd = x.m_aeb_acceleration_cmd;

                    m_aeb_acceleration_enable = x.m_aeb_acceleration_enable;

                    m_aeb_aba_request = x.m_aeb_aba_request;

                    m_aeb_aba_level = x.m_aeb_aba_level;

                    m_aeb_jerk_req = x.m_aeb_jerk_req;

                    m_aeb_jerk_level = x.m_aeb_jerk_level;

                    m_aeb_prefill_req = x.m_aeb_prefill_req;

                    m_eba_decel_req = x.m_eba_decel_req;

                    m_aeb_hold_req = x.m_aeb_hold_req;

                    m_brake_pedal_cmd = x.m_brake_pedal_cmd;

                    m_brake_pedal_cmd_enable = x.m_brake_pedal_cmd_enable;

                    m_accelration_pedal_cmd = x.m_accelration_pedal_cmd;

                    m_accelration_pedal_cmd_enble = x.m_accelration_pedal_cmd_enble;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ChassisCommand that will be copied.
     */
    eProsima_user_DllExport ChassisCommand& operator =(
            ChassisCommand&& x) noexcept
    {

        m_ads_function = x.m_ads_function;
        m_steer_angle_cmd = x.m_steer_angle_cmd;
        m_steer_wheel_torque_cmd = x.m_steer_wheel_torque_cmd;
        m_steer_vibration_cmd = x.m_steer_vibration_cmd;
        m_long_acceleration_cmd = x.m_long_acceleration_cmd;
        m_long_accelerationjerk_max = x.m_long_accelerationjerk_max;
        m_long_accelerationjerk_min = x.m_long_accelerationjerk_min;
        m_gear_cmd = x.m_gear_cmd;
        m_aeb_acceleration_cmd = x.m_aeb_acceleration_cmd;
        m_aeb_acceleration_enable = x.m_aeb_acceleration_enable;
        m_aeb_aba_request = x.m_aeb_aba_request;
        m_aeb_aba_level = x.m_aeb_aba_level;
        m_aeb_jerk_req = x.m_aeb_jerk_req;
        m_aeb_jerk_level = x.m_aeb_jerk_level;
        m_aeb_prefill_req = x.m_aeb_prefill_req;
        m_eba_decel_req = x.m_eba_decel_req;
        m_aeb_hold_req = x.m_aeb_hold_req;
        m_brake_pedal_cmd = x.m_brake_pedal_cmd;
        m_brake_pedal_cmd_enable = x.m_brake_pedal_cmd_enable;
        m_accelration_pedal_cmd = x.m_accelration_pedal_cmd;
        m_accelration_pedal_cmd_enble = x.m_accelration_pedal_cmd_enble;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x ChassisCommand object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ChassisCommand& x) const
    {
        return (m_ads_function == x.m_ads_function &&
           m_steer_angle_cmd == x.m_steer_angle_cmd &&
           m_steer_wheel_torque_cmd == x.m_steer_wheel_torque_cmd &&
           m_steer_vibration_cmd == x.m_steer_vibration_cmd &&
           m_long_acceleration_cmd == x.m_long_acceleration_cmd &&
           m_long_accelerationjerk_max == x.m_long_accelerationjerk_max &&
           m_long_accelerationjerk_min == x.m_long_accelerationjerk_min &&
           m_gear_cmd == x.m_gear_cmd &&
           m_aeb_acceleration_cmd == x.m_aeb_acceleration_cmd &&
           m_aeb_acceleration_enable == x.m_aeb_acceleration_enable &&
           m_aeb_aba_request == x.m_aeb_aba_request &&
           m_aeb_aba_level == x.m_aeb_aba_level &&
           m_aeb_jerk_req == x.m_aeb_jerk_req &&
           m_aeb_jerk_level == x.m_aeb_jerk_level &&
           m_aeb_prefill_req == x.m_aeb_prefill_req &&
           m_eba_decel_req == x.m_eba_decel_req &&
           m_aeb_hold_req == x.m_aeb_hold_req &&
           m_brake_pedal_cmd == x.m_brake_pedal_cmd &&
           m_brake_pedal_cmd_enable == x.m_brake_pedal_cmd_enable &&
           m_accelration_pedal_cmd == x.m_accelration_pedal_cmd &&
           m_accelration_pedal_cmd_enble == x.m_accelration_pedal_cmd_enble);
    }

    /*!
     * @brief Comparison operator.
     * @param x ChassisCommand object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ChassisCommand& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member ads_function
     * @param _ads_function New value for member ads_function
     */
    eProsima_user_DllExport void ads_function(
            uint32_t _ads_function)
    {
        m_ads_function = _ads_function;
    }

    /*!
     * @brief This function returns the value of member ads_function
     * @return Value of member ads_function
     */
    eProsima_user_DllExport uint32_t ads_function() const
    {
        return m_ads_function;
    }

    /*!
     * @brief This function returns a reference to member ads_function
     * @return Reference to member ads_function
     */
    eProsima_user_DllExport uint32_t& ads_function()
    {
        return m_ads_function;
    }


    /*!
     * @brief This function sets a value in member steer_angle_cmd
     * @param _steer_angle_cmd New value for member steer_angle_cmd
     */
    eProsima_user_DllExport void steer_angle_cmd(
            float _steer_angle_cmd)
    {
        m_steer_angle_cmd = _steer_angle_cmd;
    }

    /*!
     * @brief This function returns the value of member steer_angle_cmd
     * @return Value of member steer_angle_cmd
     */
    eProsima_user_DllExport float steer_angle_cmd() const
    {
        return m_steer_angle_cmd;
    }

    /*!
     * @brief This function returns a reference to member steer_angle_cmd
     * @return Reference to member steer_angle_cmd
     */
    eProsima_user_DllExport float& steer_angle_cmd()
    {
        return m_steer_angle_cmd;
    }


    /*!
     * @brief This function sets a value in member steer_wheel_torque_cmd
     * @param _steer_wheel_torque_cmd New value for member steer_wheel_torque_cmd
     */
    eProsima_user_DllExport void steer_wheel_torque_cmd(
            float _steer_wheel_torque_cmd)
    {
        m_steer_wheel_torque_cmd = _steer_wheel_torque_cmd;
    }

    /*!
     * @brief This function returns the value of member steer_wheel_torque_cmd
     * @return Value of member steer_wheel_torque_cmd
     */
    eProsima_user_DllExport float steer_wheel_torque_cmd() const
    {
        return m_steer_wheel_torque_cmd;
    }

    /*!
     * @brief This function returns a reference to member steer_wheel_torque_cmd
     * @return Reference to member steer_wheel_torque_cmd
     */
    eProsima_user_DllExport float& steer_wheel_torque_cmd()
    {
        return m_steer_wheel_torque_cmd;
    }


    /*!
     * @brief This function sets a value in member steer_vibration_cmd
     * @param _steer_vibration_cmd New value for member steer_vibration_cmd
     */
    eProsima_user_DllExport void steer_vibration_cmd(
            int8_t _steer_vibration_cmd)
    {
        m_steer_vibration_cmd = _steer_vibration_cmd;
    }

    /*!
     * @brief This function returns the value of member steer_vibration_cmd
     * @return Value of member steer_vibration_cmd
     */
    eProsima_user_DllExport int8_t steer_vibration_cmd() const
    {
        return m_steer_vibration_cmd;
    }

    /*!
     * @brief This function returns a reference to member steer_vibration_cmd
     * @return Reference to member steer_vibration_cmd
     */
    eProsima_user_DllExport int8_t& steer_vibration_cmd()
    {
        return m_steer_vibration_cmd;
    }


    /*!
     * @brief This function sets a value in member long_acceleration_cmd
     * @param _long_acceleration_cmd New value for member long_acceleration_cmd
     */
    eProsima_user_DllExport void long_acceleration_cmd(
            float _long_acceleration_cmd)
    {
        m_long_acceleration_cmd = _long_acceleration_cmd;
    }

    /*!
     * @brief This function returns the value of member long_acceleration_cmd
     * @return Value of member long_acceleration_cmd
     */
    eProsima_user_DllExport float long_acceleration_cmd() const
    {
        return m_long_acceleration_cmd;
    }

    /*!
     * @brief This function returns a reference to member long_acceleration_cmd
     * @return Reference to member long_acceleration_cmd
     */
    eProsima_user_DllExport float& long_acceleration_cmd()
    {
        return m_long_acceleration_cmd;
    }


    /*!
     * @brief This function sets a value in member long_accelerationjerk_max
     * @param _long_accelerationjerk_max New value for member long_accelerationjerk_max
     */
    eProsima_user_DllExport void long_accelerationjerk_max(
            float _long_accelerationjerk_max)
    {
        m_long_accelerationjerk_max = _long_accelerationjerk_max;
    }

    /*!
     * @brief This function returns the value of member long_accelerationjerk_max
     * @return Value of member long_accelerationjerk_max
     */
    eProsima_user_DllExport float long_accelerationjerk_max() const
    {
        return m_long_accelerationjerk_max;
    }

    /*!
     * @brief This function returns a reference to member long_accelerationjerk_max
     * @return Reference to member long_accelerationjerk_max
     */
    eProsima_user_DllExport float& long_accelerationjerk_max()
    {
        return m_long_accelerationjerk_max;
    }


    /*!
     * @brief This function sets a value in member long_accelerationjerk_min
     * @param _long_accelerationjerk_min New value for member long_accelerationjerk_min
     */
    eProsima_user_DllExport void long_accelerationjerk_min(
            float _long_accelerationjerk_min)
    {
        m_long_accelerationjerk_min = _long_accelerationjerk_min;
    }

    /*!
     * @brief This function returns the value of member long_accelerationjerk_min
     * @return Value of member long_accelerationjerk_min
     */
    eProsima_user_DllExport float long_accelerationjerk_min() const
    {
        return m_long_accelerationjerk_min;
    }

    /*!
     * @brief This function returns a reference to member long_accelerationjerk_min
     * @return Reference to member long_accelerationjerk_min
     */
    eProsima_user_DllExport float& long_accelerationjerk_min()
    {
        return m_long_accelerationjerk_min;
    }


    /*!
     * @brief This function sets a value in member gear_cmd
     * @param _gear_cmd New value for member gear_cmd
     */
    eProsima_user_DllExport void gear_cmd(
            int8_t _gear_cmd)
    {
        m_gear_cmd = _gear_cmd;
    }

    /*!
     * @brief This function returns the value of member gear_cmd
     * @return Value of member gear_cmd
     */
    eProsima_user_DllExport int8_t gear_cmd() const
    {
        return m_gear_cmd;
    }

    /*!
     * @brief This function returns a reference to member gear_cmd
     * @return Reference to member gear_cmd
     */
    eProsima_user_DllExport int8_t& gear_cmd()
    {
        return m_gear_cmd;
    }


    /*!
     * @brief This function sets a value in member aeb_acceleration_cmd
     * @param _aeb_acceleration_cmd New value for member aeb_acceleration_cmd
     */
    eProsima_user_DllExport void aeb_acceleration_cmd(
            float _aeb_acceleration_cmd)
    {
        m_aeb_acceleration_cmd = _aeb_acceleration_cmd;
    }

    /*!
     * @brief This function returns the value of member aeb_acceleration_cmd
     * @return Value of member aeb_acceleration_cmd
     */
    eProsima_user_DllExport float aeb_acceleration_cmd() const
    {
        return m_aeb_acceleration_cmd;
    }

    /*!
     * @brief This function returns a reference to member aeb_acceleration_cmd
     * @return Reference to member aeb_acceleration_cmd
     */
    eProsima_user_DllExport float& aeb_acceleration_cmd()
    {
        return m_aeb_acceleration_cmd;
    }


    /*!
     * @brief This function sets a value in member aeb_acceleration_enable
     * @param _aeb_acceleration_enable New value for member aeb_acceleration_enable
     */
    eProsima_user_DllExport void aeb_acceleration_enable(
            bool _aeb_acceleration_enable)
    {
        m_aeb_acceleration_enable = _aeb_acceleration_enable;
    }

    /*!
     * @brief This function returns the value of member aeb_acceleration_enable
     * @return Value of member aeb_acceleration_enable
     */
    eProsima_user_DllExport bool aeb_acceleration_enable() const
    {
        return m_aeb_acceleration_enable;
    }

    /*!
     * @brief This function returns a reference to member aeb_acceleration_enable
     * @return Reference to member aeb_acceleration_enable
     */
    eProsima_user_DllExport bool& aeb_acceleration_enable()
    {
        return m_aeb_acceleration_enable;
    }


    /*!
     * @brief This function sets a value in member aeb_aba_request
     * @param _aeb_aba_request New value for member aeb_aba_request
     */
    eProsima_user_DllExport void aeb_aba_request(
            bool _aeb_aba_request)
    {
        m_aeb_aba_request = _aeb_aba_request;
    }

    /*!
     * @brief This function returns the value of member aeb_aba_request
     * @return Value of member aeb_aba_request
     */
    eProsima_user_DllExport bool aeb_aba_request() const
    {
        return m_aeb_aba_request;
    }

    /*!
     * @brief This function returns a reference to member aeb_aba_request
     * @return Reference to member aeb_aba_request
     */
    eProsima_user_DllExport bool& aeb_aba_request()
    {
        return m_aeb_aba_request;
    }


    /*!
     * @brief This function sets a value in member aeb_aba_level
     * @param _aeb_aba_level New value for member aeb_aba_level
     */
    eProsima_user_DllExport void aeb_aba_level(
            int8_t _aeb_aba_level)
    {
        m_aeb_aba_level = _aeb_aba_level;
    }

    /*!
     * @brief This function returns the value of member aeb_aba_level
     * @return Value of member aeb_aba_level
     */
    eProsima_user_DllExport int8_t aeb_aba_level() const
    {
        return m_aeb_aba_level;
    }

    /*!
     * @brief This function returns a reference to member aeb_aba_level
     * @return Reference to member aeb_aba_level
     */
    eProsima_user_DllExport int8_t& aeb_aba_level()
    {
        return m_aeb_aba_level;
    }


    /*!
     * @brief This function sets a value in member aeb_jerk_req
     * @param _aeb_jerk_req New value for member aeb_jerk_req
     */
    eProsima_user_DllExport void aeb_jerk_req(
            bool _aeb_jerk_req)
    {
        m_aeb_jerk_req = _aeb_jerk_req;
    }

    /*!
     * @brief This function returns the value of member aeb_jerk_req
     * @return Value of member aeb_jerk_req
     */
    eProsima_user_DllExport bool aeb_jerk_req() const
    {
        return m_aeb_jerk_req;
    }

    /*!
     * @brief This function returns a reference to member aeb_jerk_req
     * @return Reference to member aeb_jerk_req
     */
    eProsima_user_DllExport bool& aeb_jerk_req()
    {
        return m_aeb_jerk_req;
    }


    /*!
     * @brief This function sets a value in member aeb_jerk_level
     * @param _aeb_jerk_level New value for member aeb_jerk_level
     */
    eProsima_user_DllExport void aeb_jerk_level(
            int8_t _aeb_jerk_level)
    {
        m_aeb_jerk_level = _aeb_jerk_level;
    }

    /*!
     * @brief This function returns the value of member aeb_jerk_level
     * @return Value of member aeb_jerk_level
     */
    eProsima_user_DllExport int8_t aeb_jerk_level() const
    {
        return m_aeb_jerk_level;
    }

    /*!
     * @brief This function returns a reference to member aeb_jerk_level
     * @return Reference to member aeb_jerk_level
     */
    eProsima_user_DllExport int8_t& aeb_jerk_level()
    {
        return m_aeb_jerk_level;
    }


    /*!
     * @brief This function sets a value in member aeb_prefill_req
     * @param _aeb_prefill_req New value for member aeb_prefill_req
     */
    eProsima_user_DllExport void aeb_prefill_req(
            bool _aeb_prefill_req)
    {
        m_aeb_prefill_req = _aeb_prefill_req;
    }

    /*!
     * @brief This function returns the value of member aeb_prefill_req
     * @return Value of member aeb_prefill_req
     */
    eProsima_user_DllExport bool aeb_prefill_req() const
    {
        return m_aeb_prefill_req;
    }

    /*!
     * @brief This function returns a reference to member aeb_prefill_req
     * @return Reference to member aeb_prefill_req
     */
    eProsima_user_DllExport bool& aeb_prefill_req()
    {
        return m_aeb_prefill_req;
    }


    /*!
     * @brief This function sets a value in member eba_decel_req
     * @param _eba_decel_req New value for member eba_decel_req
     */
    eProsima_user_DllExport void eba_decel_req(
            bool _eba_decel_req)
    {
        m_eba_decel_req = _eba_decel_req;
    }

    /*!
     * @brief This function returns the value of member eba_decel_req
     * @return Value of member eba_decel_req
     */
    eProsima_user_DllExport bool eba_decel_req() const
    {
        return m_eba_decel_req;
    }

    /*!
     * @brief This function returns a reference to member eba_decel_req
     * @return Reference to member eba_decel_req
     */
    eProsima_user_DllExport bool& eba_decel_req()
    {
        return m_eba_decel_req;
    }


    /*!
     * @brief This function sets a value in member aeb_hold_req
     * @param _aeb_hold_req New value for member aeb_hold_req
     */
    eProsima_user_DllExport void aeb_hold_req(
            bool _aeb_hold_req)
    {
        m_aeb_hold_req = _aeb_hold_req;
    }

    /*!
     * @brief This function returns the value of member aeb_hold_req
     * @return Value of member aeb_hold_req
     */
    eProsima_user_DllExport bool aeb_hold_req() const
    {
        return m_aeb_hold_req;
    }

    /*!
     * @brief This function returns a reference to member aeb_hold_req
     * @return Reference to member aeb_hold_req
     */
    eProsima_user_DllExport bool& aeb_hold_req()
    {
        return m_aeb_hold_req;
    }


    /*!
     * @brief This function sets a value in member brake_pedal_cmd
     * @param _brake_pedal_cmd New value for member brake_pedal_cmd
     */
    eProsima_user_DllExport void brake_pedal_cmd(
            uint8_t _brake_pedal_cmd)
    {
        m_brake_pedal_cmd = _brake_pedal_cmd;
    }

    /*!
     * @brief This function returns the value of member brake_pedal_cmd
     * @return Value of member brake_pedal_cmd
     */
    eProsima_user_DllExport uint8_t brake_pedal_cmd() const
    {
        return m_brake_pedal_cmd;
    }

    /*!
     * @brief This function returns a reference to member brake_pedal_cmd
     * @return Reference to member brake_pedal_cmd
     */
    eProsima_user_DllExport uint8_t& brake_pedal_cmd()
    {
        return m_brake_pedal_cmd;
    }


    /*!
     * @brief This function sets a value in member brake_pedal_cmd_enable
     * @param _brake_pedal_cmd_enable New value for member brake_pedal_cmd_enable
     */
    eProsima_user_DllExport void brake_pedal_cmd_enable(
            bool _brake_pedal_cmd_enable)
    {
        m_brake_pedal_cmd_enable = _brake_pedal_cmd_enable;
    }

    /*!
     * @brief This function returns the value of member brake_pedal_cmd_enable
     * @return Value of member brake_pedal_cmd_enable
     */
    eProsima_user_DllExport bool brake_pedal_cmd_enable() const
    {
        return m_brake_pedal_cmd_enable;
    }

    /*!
     * @brief This function returns a reference to member brake_pedal_cmd_enable
     * @return Reference to member brake_pedal_cmd_enable
     */
    eProsima_user_DllExport bool& brake_pedal_cmd_enable()
    {
        return m_brake_pedal_cmd_enable;
    }


    /*!
     * @brief This function sets a value in member accelration_pedal_cmd
     * @param _accelration_pedal_cmd New value for member accelration_pedal_cmd
     */
    eProsima_user_DllExport void accelration_pedal_cmd(
            uint8_t _accelration_pedal_cmd)
    {
        m_accelration_pedal_cmd = _accelration_pedal_cmd;
    }

    /*!
     * @brief This function returns the value of member accelration_pedal_cmd
     * @return Value of member accelration_pedal_cmd
     */
    eProsima_user_DllExport uint8_t accelration_pedal_cmd() const
    {
        return m_accelration_pedal_cmd;
    }

    /*!
     * @brief This function returns a reference to member accelration_pedal_cmd
     * @return Reference to member accelration_pedal_cmd
     */
    eProsima_user_DllExport uint8_t& accelration_pedal_cmd()
    {
        return m_accelration_pedal_cmd;
    }


    /*!
     * @brief This function sets a value in member accelration_pedal_cmd_enble
     * @param _accelration_pedal_cmd_enble New value for member accelration_pedal_cmd_enble
     */
    eProsima_user_DllExport void accelration_pedal_cmd_enble(
            bool _accelration_pedal_cmd_enble)
    {
        m_accelration_pedal_cmd_enble = _accelration_pedal_cmd_enble;
    }

    /*!
     * @brief This function returns the value of member accelration_pedal_cmd_enble
     * @return Value of member accelration_pedal_cmd_enble
     */
    eProsima_user_DllExport bool accelration_pedal_cmd_enble() const
    {
        return m_accelration_pedal_cmd_enble;
    }

    /*!
     * @brief This function returns a reference to member accelration_pedal_cmd_enble
     * @return Reference to member accelration_pedal_cmd_enble
     */
    eProsima_user_DllExport bool& accelration_pedal_cmd_enble()
    {
        return m_accelration_pedal_cmd_enble;
    }



private:

    uint32_t m_ads_function{0};
    float m_steer_angle_cmd{0.0};
    float m_steer_wheel_torque_cmd{0.0};
    int8_t m_steer_vibration_cmd{0};
    float m_long_acceleration_cmd{0.0};
    float m_long_accelerationjerk_max{0.0};
    float m_long_accelerationjerk_min{0.0};
    int8_t m_gear_cmd{0};
    float m_aeb_acceleration_cmd{0.0};
    bool m_aeb_acceleration_enable{false};
    bool m_aeb_aba_request{false};
    int8_t m_aeb_aba_level{0};
    bool m_aeb_jerk_req{false};
    int8_t m_aeb_jerk_level{0};
    bool m_aeb_prefill_req{false};
    bool m_eba_decel_req{false};
    bool m_aeb_hold_req{false};
    uint8_t m_brake_pedal_cmd{0};
    bool m_brake_pedal_cmd_enable{false};
    uint8_t m_accelration_pedal_cmd{0};
    bool m_accelration_pedal_cmd_enble{false};

};

} // namespace msg

} // namespace control_msgs

#endif // _FAST_DDS_GENERATED_CONTROL_MSGS_MSG_CHASSISCOMMAND_HPP_


