// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ChassisCommandTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.2.0).
 */

#include "ChassisCommandTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "ChassisCommand.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace control_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_ChassisCommand_type_identifier(
        TypeIdentifierPair& type_ids_ChassisCommand)
{

    ReturnCode_t return_code_ChassisCommand {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ChassisCommand =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "control_msgs::msg::dds_::ChassisCommand_", type_ids_ChassisCommand);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChassisCommand)
    {
        StructTypeFlag struct_flags_ChassisCommand = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_ChassisCommand = "control_msgs::msg::dds_::ChassisCommand_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ChassisCommand;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ChassisCommand;
        CompleteTypeDetail detail_ChassisCommand = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ChassisCommand, ann_custom_ChassisCommand, type_name_ChassisCommand.to_string());
        CompleteStructHeader header_ChassisCommand;
        header_ChassisCommand = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_ChassisCommand);
        CompleteStructMemberSeq member_seq_ChassisCommand;
        {
            TypeIdentifierPair type_ids_ads_function;
            ReturnCode_t return_code_ads_function {eprosima::fastdds::dds::RETCODE_OK};
            return_code_ads_function =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_ads_function);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ads_function)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "ads_function Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_ads_function = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_ads_function = 0x00000000;
            bool common_ads_function_ec {false};
            CommonStructMember common_ads_function {TypeObjectUtils::build_common_struct_member(member_id_ads_function, member_flags_ads_function, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ads_function, common_ads_function_ec))};
            if (!common_ads_function_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure ads_function member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_ads_function = "ads_function";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ads_function;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_ads_function = TypeObjectUtils::build_complete_member_detail(name_ads_function, member_ann_builtin_ads_function, ann_custom_ChassisCommand);
            CompleteStructMember member_ads_function = TypeObjectUtils::build_complete_struct_member(common_ads_function, detail_ads_function);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_ads_function);
        }
        {
            TypeIdentifierPair type_ids_steer_angle_cmd;
            ReturnCode_t return_code_steer_angle_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_steer_angle_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_steer_angle_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_steer_angle_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "steer_angle_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_steer_angle_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_steer_angle_cmd = 0x00000001;
            bool common_steer_angle_cmd_ec {false};
            CommonStructMember common_steer_angle_cmd {TypeObjectUtils::build_common_struct_member(member_id_steer_angle_cmd, member_flags_steer_angle_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_steer_angle_cmd, common_steer_angle_cmd_ec))};
            if (!common_steer_angle_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure steer_angle_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_steer_angle_cmd = "steer_angle_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_steer_angle_cmd;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_steer_angle_cmd = TypeObjectUtils::build_complete_member_detail(name_steer_angle_cmd, member_ann_builtin_steer_angle_cmd, ann_custom_ChassisCommand);
            CompleteStructMember member_steer_angle_cmd = TypeObjectUtils::build_complete_struct_member(common_steer_angle_cmd, detail_steer_angle_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_steer_angle_cmd);
        }
        {
            TypeIdentifierPair type_ids_steer_wheel_torque_cmd;
            ReturnCode_t return_code_steer_wheel_torque_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_steer_wheel_torque_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_steer_wheel_torque_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_steer_wheel_torque_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "steer_wheel_torque_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_steer_wheel_torque_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_steer_wheel_torque_cmd = 0x00000002;
            bool common_steer_wheel_torque_cmd_ec {false};
            CommonStructMember common_steer_wheel_torque_cmd {TypeObjectUtils::build_common_struct_member(member_id_steer_wheel_torque_cmd, member_flags_steer_wheel_torque_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_steer_wheel_torque_cmd, common_steer_wheel_torque_cmd_ec))};
            if (!common_steer_wheel_torque_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure steer_wheel_torque_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_steer_wheel_torque_cmd = "steer_wheel_torque_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_steer_wheel_torque_cmd;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_steer_wheel_torque_cmd = TypeObjectUtils::build_complete_member_detail(name_steer_wheel_torque_cmd, member_ann_builtin_steer_wheel_torque_cmd, ann_custom_ChassisCommand);
            CompleteStructMember member_steer_wheel_torque_cmd = TypeObjectUtils::build_complete_struct_member(common_steer_wheel_torque_cmd, detail_steer_wheel_torque_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_steer_wheel_torque_cmd);
        }
        {
            TypeIdentifierPair type_ids_steer_vibration_cmd;
            ReturnCode_t return_code_steer_vibration_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_steer_vibration_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_steer_vibration_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_steer_vibration_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "steer_vibration_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_steer_vibration_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_steer_vibration_cmd = 0x00000003;
            bool common_steer_vibration_cmd_ec {false};
            CommonStructMember common_steer_vibration_cmd {TypeObjectUtils::build_common_struct_member(member_id_steer_vibration_cmd, member_flags_steer_vibration_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_steer_vibration_cmd, common_steer_vibration_cmd_ec))};
            if (!common_steer_vibration_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure steer_vibration_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_steer_vibration_cmd = "steer_vibration_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_steer_vibration_cmd;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_steer_vibration_cmd = TypeObjectUtils::build_complete_member_detail(name_steer_vibration_cmd, member_ann_builtin_steer_vibration_cmd, ann_custom_ChassisCommand);
            CompleteStructMember member_steer_vibration_cmd = TypeObjectUtils::build_complete_struct_member(common_steer_vibration_cmd, detail_steer_vibration_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_steer_vibration_cmd);
        }
        {
            TypeIdentifierPair type_ids_long_acceleration_cmd;
            ReturnCode_t return_code_long_acceleration_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_long_acceleration_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_long_acceleration_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_long_acceleration_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "long_acceleration_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_long_acceleration_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_long_acceleration_cmd = 0x00000004;
            bool common_long_acceleration_cmd_ec {false};
            CommonStructMember common_long_acceleration_cmd {TypeObjectUtils::build_common_struct_member(member_id_long_acceleration_cmd, member_flags_long_acceleration_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_long_acceleration_cmd, common_long_acceleration_cmd_ec))};
            if (!common_long_acceleration_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure long_acceleration_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_long_acceleration_cmd = "long_acceleration_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_long_acceleration_cmd;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_long_acceleration_cmd = TypeObjectUtils::build_complete_member_detail(name_long_acceleration_cmd, member_ann_builtin_long_acceleration_cmd, ann_custom_ChassisCommand);
            CompleteStructMember member_long_acceleration_cmd = TypeObjectUtils::build_complete_struct_member(common_long_acceleration_cmd, detail_long_acceleration_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_long_acceleration_cmd);
        }
        {
            TypeIdentifierPair type_ids_long_accelerationjerk_max;
            ReturnCode_t return_code_long_accelerationjerk_max {eprosima::fastdds::dds::RETCODE_OK};
            return_code_long_accelerationjerk_max =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_long_accelerationjerk_max);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_long_accelerationjerk_max)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "long_accelerationjerk_max Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_long_accelerationjerk_max = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_long_accelerationjerk_max = 0x00000005;
            bool common_long_accelerationjerk_max_ec {false};
            CommonStructMember common_long_accelerationjerk_max {TypeObjectUtils::build_common_struct_member(member_id_long_accelerationjerk_max, member_flags_long_accelerationjerk_max, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_long_accelerationjerk_max, common_long_accelerationjerk_max_ec))};
            if (!common_long_accelerationjerk_max_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure long_accelerationjerk_max member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_long_accelerationjerk_max = "long_accelerationjerk_max";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_long_accelerationjerk_max;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_long_accelerationjerk_max = TypeObjectUtils::build_complete_member_detail(name_long_accelerationjerk_max, member_ann_builtin_long_accelerationjerk_max, ann_custom_ChassisCommand);
            CompleteStructMember member_long_accelerationjerk_max = TypeObjectUtils::build_complete_struct_member(common_long_accelerationjerk_max, detail_long_accelerationjerk_max);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_long_accelerationjerk_max);
        }
        {
            TypeIdentifierPair type_ids_long_accelerationjerk_min;
            ReturnCode_t return_code_long_accelerationjerk_min {eprosima::fastdds::dds::RETCODE_OK};
            return_code_long_accelerationjerk_min =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_long_accelerationjerk_min);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_long_accelerationjerk_min)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "long_accelerationjerk_min Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_long_accelerationjerk_min = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_long_accelerationjerk_min = 0x00000006;
            bool common_long_accelerationjerk_min_ec {false};
            CommonStructMember common_long_accelerationjerk_min {TypeObjectUtils::build_common_struct_member(member_id_long_accelerationjerk_min, member_flags_long_accelerationjerk_min, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_long_accelerationjerk_min, common_long_accelerationjerk_min_ec))};
            if (!common_long_accelerationjerk_min_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure long_accelerationjerk_min member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_long_accelerationjerk_min = "long_accelerationjerk_min";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_long_accelerationjerk_min;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_long_accelerationjerk_min = TypeObjectUtils::build_complete_member_detail(name_long_accelerationjerk_min, member_ann_builtin_long_accelerationjerk_min, ann_custom_ChassisCommand);
            CompleteStructMember member_long_accelerationjerk_min = TypeObjectUtils::build_complete_struct_member(common_long_accelerationjerk_min, detail_long_accelerationjerk_min);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_long_accelerationjerk_min);
        }
        {
            TypeIdentifierPair type_ids_gear_cmd;
            ReturnCode_t return_code_gear_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_gear_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_gear_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_gear_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "gear_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_gear_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_gear_cmd = 0x00000007;
            bool common_gear_cmd_ec {false};
            CommonStructMember common_gear_cmd {TypeObjectUtils::build_common_struct_member(member_id_gear_cmd, member_flags_gear_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_gear_cmd, common_gear_cmd_ec))};
            if (!common_gear_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure gear_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_gear_cmd = "gear_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_gear_cmd;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_gear_cmd = TypeObjectUtils::build_complete_member_detail(name_gear_cmd, member_ann_builtin_gear_cmd, ann_custom_ChassisCommand);
            CompleteStructMember member_gear_cmd = TypeObjectUtils::build_complete_struct_member(common_gear_cmd, detail_gear_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_gear_cmd);
        }
        {
            TypeIdentifierPair type_ids_aeb_acceleration_cmd;
            ReturnCode_t return_code_aeb_acceleration_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_aeb_acceleration_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_aeb_acceleration_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_aeb_acceleration_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "aeb_acceleration_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_aeb_acceleration_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_aeb_acceleration_cmd = 0x00000008;
            bool common_aeb_acceleration_cmd_ec {false};
            CommonStructMember common_aeb_acceleration_cmd {TypeObjectUtils::build_common_struct_member(member_id_aeb_acceleration_cmd, member_flags_aeb_acceleration_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_aeb_acceleration_cmd, common_aeb_acceleration_cmd_ec))};
            if (!common_aeb_acceleration_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure aeb_acceleration_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_aeb_acceleration_cmd = "aeb_acceleration_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_aeb_acceleration_cmd;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_aeb_acceleration_cmd = TypeObjectUtils::build_complete_member_detail(name_aeb_acceleration_cmd, member_ann_builtin_aeb_acceleration_cmd, ann_custom_ChassisCommand);
            CompleteStructMember member_aeb_acceleration_cmd = TypeObjectUtils::build_complete_struct_member(common_aeb_acceleration_cmd, detail_aeb_acceleration_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_aeb_acceleration_cmd);
        }
        {
            TypeIdentifierPair type_ids_aeb_acceleration_enable;
            ReturnCode_t return_code_aeb_acceleration_enable {eprosima::fastdds::dds::RETCODE_OK};
            return_code_aeb_acceleration_enable =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_aeb_acceleration_enable);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_aeb_acceleration_enable)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "aeb_acceleration_enable Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_aeb_acceleration_enable = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_aeb_acceleration_enable = 0x00000009;
            bool common_aeb_acceleration_enable_ec {false};
            CommonStructMember common_aeb_acceleration_enable {TypeObjectUtils::build_common_struct_member(member_id_aeb_acceleration_enable, member_flags_aeb_acceleration_enable, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_aeb_acceleration_enable, common_aeb_acceleration_enable_ec))};
            if (!common_aeb_acceleration_enable_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure aeb_acceleration_enable member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_aeb_acceleration_enable = "aeb_acceleration_enable";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_aeb_acceleration_enable;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_aeb_acceleration_enable = TypeObjectUtils::build_complete_member_detail(name_aeb_acceleration_enable, member_ann_builtin_aeb_acceleration_enable, ann_custom_ChassisCommand);
            CompleteStructMember member_aeb_acceleration_enable = TypeObjectUtils::build_complete_struct_member(common_aeb_acceleration_enable, detail_aeb_acceleration_enable);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_aeb_acceleration_enable);
        }
        {
            TypeIdentifierPair type_ids_aeb_aba_request;
            ReturnCode_t return_code_aeb_aba_request {eprosima::fastdds::dds::RETCODE_OK};
            return_code_aeb_aba_request =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_aeb_aba_request);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_aeb_aba_request)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "aeb_aba_request Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_aeb_aba_request = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_aeb_aba_request = 0x0000000a;
            bool common_aeb_aba_request_ec {false};
            CommonStructMember common_aeb_aba_request {TypeObjectUtils::build_common_struct_member(member_id_aeb_aba_request, member_flags_aeb_aba_request, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_aeb_aba_request, common_aeb_aba_request_ec))};
            if (!common_aeb_aba_request_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure aeb_aba_request member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_aeb_aba_request = "aeb_aba_request";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_aeb_aba_request;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_aeb_aba_request = TypeObjectUtils::build_complete_member_detail(name_aeb_aba_request, member_ann_builtin_aeb_aba_request, ann_custom_ChassisCommand);
            CompleteStructMember member_aeb_aba_request = TypeObjectUtils::build_complete_struct_member(common_aeb_aba_request, detail_aeb_aba_request);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_aeb_aba_request);
        }
        {
            TypeIdentifierPair type_ids_aeb_aba_level;
            ReturnCode_t return_code_aeb_aba_level {eprosima::fastdds::dds::RETCODE_OK};
            return_code_aeb_aba_level =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_aeb_aba_level);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_aeb_aba_level)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "aeb_aba_level Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_aeb_aba_level = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_aeb_aba_level = 0x0000000b;
            bool common_aeb_aba_level_ec {false};
            CommonStructMember common_aeb_aba_level {TypeObjectUtils::build_common_struct_member(member_id_aeb_aba_level, member_flags_aeb_aba_level, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_aeb_aba_level, common_aeb_aba_level_ec))};
            if (!common_aeb_aba_level_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure aeb_aba_level member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_aeb_aba_level = "aeb_aba_level";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_aeb_aba_level;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_aeb_aba_level = TypeObjectUtils::build_complete_member_detail(name_aeb_aba_level, member_ann_builtin_aeb_aba_level, ann_custom_ChassisCommand);
            CompleteStructMember member_aeb_aba_level = TypeObjectUtils::build_complete_struct_member(common_aeb_aba_level, detail_aeb_aba_level);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_aeb_aba_level);
        }
        {
            TypeIdentifierPair type_ids_aeb_jerk_req;
            ReturnCode_t return_code_aeb_jerk_req {eprosima::fastdds::dds::RETCODE_OK};
            return_code_aeb_jerk_req =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_aeb_jerk_req);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_aeb_jerk_req)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "aeb_jerk_req Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_aeb_jerk_req = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_aeb_jerk_req = 0x0000000c;
            bool common_aeb_jerk_req_ec {false};
            CommonStructMember common_aeb_jerk_req {TypeObjectUtils::build_common_struct_member(member_id_aeb_jerk_req, member_flags_aeb_jerk_req, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_aeb_jerk_req, common_aeb_jerk_req_ec))};
            if (!common_aeb_jerk_req_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure aeb_jerk_req member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_aeb_jerk_req = "aeb_jerk_req";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_aeb_jerk_req;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_aeb_jerk_req = TypeObjectUtils::build_complete_member_detail(name_aeb_jerk_req, member_ann_builtin_aeb_jerk_req, ann_custom_ChassisCommand);
            CompleteStructMember member_aeb_jerk_req = TypeObjectUtils::build_complete_struct_member(common_aeb_jerk_req, detail_aeb_jerk_req);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_aeb_jerk_req);
        }
        {
            TypeIdentifierPair type_ids_aeb_jerk_level;
            ReturnCode_t return_code_aeb_jerk_level {eprosima::fastdds::dds::RETCODE_OK};
            return_code_aeb_jerk_level =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int8_t", type_ids_aeb_jerk_level);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_aeb_jerk_level)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "aeb_jerk_level Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_aeb_jerk_level = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_aeb_jerk_level = 0x0000000d;
            bool common_aeb_jerk_level_ec {false};
            CommonStructMember common_aeb_jerk_level {TypeObjectUtils::build_common_struct_member(member_id_aeb_jerk_level, member_flags_aeb_jerk_level, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_aeb_jerk_level, common_aeb_jerk_level_ec))};
            if (!common_aeb_jerk_level_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure aeb_jerk_level member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_aeb_jerk_level = "aeb_jerk_level";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_aeb_jerk_level;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_aeb_jerk_level = TypeObjectUtils::build_complete_member_detail(name_aeb_jerk_level, member_ann_builtin_aeb_jerk_level, ann_custom_ChassisCommand);
            CompleteStructMember member_aeb_jerk_level = TypeObjectUtils::build_complete_struct_member(common_aeb_jerk_level, detail_aeb_jerk_level);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_aeb_jerk_level);
        }
        {
            TypeIdentifierPair type_ids_aeb_prefill_req;
            ReturnCode_t return_code_aeb_prefill_req {eprosima::fastdds::dds::RETCODE_OK};
            return_code_aeb_prefill_req =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_aeb_prefill_req);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_aeb_prefill_req)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "aeb_prefill_req Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_aeb_prefill_req = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_aeb_prefill_req = 0x0000000e;
            bool common_aeb_prefill_req_ec {false};
            CommonStructMember common_aeb_prefill_req {TypeObjectUtils::build_common_struct_member(member_id_aeb_prefill_req, member_flags_aeb_prefill_req, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_aeb_prefill_req, common_aeb_prefill_req_ec))};
            if (!common_aeb_prefill_req_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure aeb_prefill_req member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_aeb_prefill_req = "aeb_prefill_req";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_aeb_prefill_req;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_aeb_prefill_req = TypeObjectUtils::build_complete_member_detail(name_aeb_prefill_req, member_ann_builtin_aeb_prefill_req, ann_custom_ChassisCommand);
            CompleteStructMember member_aeb_prefill_req = TypeObjectUtils::build_complete_struct_member(common_aeb_prefill_req, detail_aeb_prefill_req);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_aeb_prefill_req);
        }
        {
            TypeIdentifierPair type_ids_eba_decel_req;
            ReturnCode_t return_code_eba_decel_req {eprosima::fastdds::dds::RETCODE_OK};
            return_code_eba_decel_req =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_eba_decel_req);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_eba_decel_req)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "eba_decel_req Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_eba_decel_req = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_eba_decel_req = 0x0000000f;
            bool common_eba_decel_req_ec {false};
            CommonStructMember common_eba_decel_req {TypeObjectUtils::build_common_struct_member(member_id_eba_decel_req, member_flags_eba_decel_req, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_eba_decel_req, common_eba_decel_req_ec))};
            if (!common_eba_decel_req_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure eba_decel_req member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_eba_decel_req = "eba_decel_req";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_eba_decel_req;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_eba_decel_req = TypeObjectUtils::build_complete_member_detail(name_eba_decel_req, member_ann_builtin_eba_decel_req, ann_custom_ChassisCommand);
            CompleteStructMember member_eba_decel_req = TypeObjectUtils::build_complete_struct_member(common_eba_decel_req, detail_eba_decel_req);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_eba_decel_req);
        }
        {
            TypeIdentifierPair type_ids_aeb_hold_req;
            ReturnCode_t return_code_aeb_hold_req {eprosima::fastdds::dds::RETCODE_OK};
            return_code_aeb_hold_req =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_aeb_hold_req);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_aeb_hold_req)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "aeb_hold_req Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_aeb_hold_req = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_aeb_hold_req = 0x00000010;
            bool common_aeb_hold_req_ec {false};
            CommonStructMember common_aeb_hold_req {TypeObjectUtils::build_common_struct_member(member_id_aeb_hold_req, member_flags_aeb_hold_req, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_aeb_hold_req, common_aeb_hold_req_ec))};
            if (!common_aeb_hold_req_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure aeb_hold_req member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_aeb_hold_req = "aeb_hold_req";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_aeb_hold_req;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_aeb_hold_req = TypeObjectUtils::build_complete_member_detail(name_aeb_hold_req, member_ann_builtin_aeb_hold_req, ann_custom_ChassisCommand);
            CompleteStructMember member_aeb_hold_req = TypeObjectUtils::build_complete_struct_member(common_aeb_hold_req, detail_aeb_hold_req);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_aeb_hold_req);
        }
        {
            TypeIdentifierPair type_ids_brake_pedal_cmd;
            ReturnCode_t return_code_brake_pedal_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_brake_pedal_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint8_t", type_ids_brake_pedal_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_brake_pedal_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "brake_pedal_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_brake_pedal_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_brake_pedal_cmd = 0x00000011;
            bool common_brake_pedal_cmd_ec {false};
            CommonStructMember common_brake_pedal_cmd {TypeObjectUtils::build_common_struct_member(member_id_brake_pedal_cmd, member_flags_brake_pedal_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_brake_pedal_cmd, common_brake_pedal_cmd_ec))};
            if (!common_brake_pedal_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure brake_pedal_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_brake_pedal_cmd = "brake_pedal_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_brake_pedal_cmd;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_brake_pedal_cmd = TypeObjectUtils::build_complete_member_detail(name_brake_pedal_cmd, member_ann_builtin_brake_pedal_cmd, ann_custom_ChassisCommand);
            CompleteStructMember member_brake_pedal_cmd = TypeObjectUtils::build_complete_struct_member(common_brake_pedal_cmd, detail_brake_pedal_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_brake_pedal_cmd);
        }
        {
            TypeIdentifierPair type_ids_brake_pedal_cmd_enable;
            ReturnCode_t return_code_brake_pedal_cmd_enable {eprosima::fastdds::dds::RETCODE_OK};
            return_code_brake_pedal_cmd_enable =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_brake_pedal_cmd_enable);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_brake_pedal_cmd_enable)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "brake_pedal_cmd_enable Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_brake_pedal_cmd_enable = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_brake_pedal_cmd_enable = 0x00000012;
            bool common_brake_pedal_cmd_enable_ec {false};
            CommonStructMember common_brake_pedal_cmd_enable {TypeObjectUtils::build_common_struct_member(member_id_brake_pedal_cmd_enable, member_flags_brake_pedal_cmd_enable, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_brake_pedal_cmd_enable, common_brake_pedal_cmd_enable_ec))};
            if (!common_brake_pedal_cmd_enable_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure brake_pedal_cmd_enable member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_brake_pedal_cmd_enable = "brake_pedal_cmd_enable";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_brake_pedal_cmd_enable;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_brake_pedal_cmd_enable = TypeObjectUtils::build_complete_member_detail(name_brake_pedal_cmd_enable, member_ann_builtin_brake_pedal_cmd_enable, ann_custom_ChassisCommand);
            CompleteStructMember member_brake_pedal_cmd_enable = TypeObjectUtils::build_complete_struct_member(common_brake_pedal_cmd_enable, detail_brake_pedal_cmd_enable);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_brake_pedal_cmd_enable);
        }
        {
            TypeIdentifierPair type_ids_accelration_pedal_cmd;
            ReturnCode_t return_code_accelration_pedal_cmd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_accelration_pedal_cmd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint8_t", type_ids_accelration_pedal_cmd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_accelration_pedal_cmd)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "accelration_pedal_cmd Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_accelration_pedal_cmd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_accelration_pedal_cmd = 0x00000013;
            bool common_accelration_pedal_cmd_ec {false};
            CommonStructMember common_accelration_pedal_cmd {TypeObjectUtils::build_common_struct_member(member_id_accelration_pedal_cmd, member_flags_accelration_pedal_cmd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_accelration_pedal_cmd, common_accelration_pedal_cmd_ec))};
            if (!common_accelration_pedal_cmd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure accelration_pedal_cmd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_accelration_pedal_cmd = "accelration_pedal_cmd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_accelration_pedal_cmd;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_accelration_pedal_cmd = TypeObjectUtils::build_complete_member_detail(name_accelration_pedal_cmd, member_ann_builtin_accelration_pedal_cmd, ann_custom_ChassisCommand);
            CompleteStructMember member_accelration_pedal_cmd = TypeObjectUtils::build_complete_struct_member(common_accelration_pedal_cmd, detail_accelration_pedal_cmd);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_accelration_pedal_cmd);
        }
        {
            TypeIdentifierPair type_ids_accelration_pedal_cmd_enble;
            ReturnCode_t return_code_accelration_pedal_cmd_enble {eprosima::fastdds::dds::RETCODE_OK};
            return_code_accelration_pedal_cmd_enble =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_accelration_pedal_cmd_enble);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_accelration_pedal_cmd_enble)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "accelration_pedal_cmd_enble Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_accelration_pedal_cmd_enble = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_accelration_pedal_cmd_enble = 0x00000014;
            bool common_accelration_pedal_cmd_enble_ec {false};
            CommonStructMember common_accelration_pedal_cmd_enble {TypeObjectUtils::build_common_struct_member(member_id_accelration_pedal_cmd_enble, member_flags_accelration_pedal_cmd_enble, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_accelration_pedal_cmd_enble, common_accelration_pedal_cmd_enble_ec))};
            if (!common_accelration_pedal_cmd_enble_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure accelration_pedal_cmd_enble member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_accelration_pedal_cmd_enble = "accelration_pedal_cmd_enble";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_accelration_pedal_cmd_enble;
            ann_custom_ChassisCommand.reset();
            CompleteMemberDetail detail_accelration_pedal_cmd_enble = TypeObjectUtils::build_complete_member_detail(name_accelration_pedal_cmd_enble, member_ann_builtin_accelration_pedal_cmd_enble, ann_custom_ChassisCommand);
            CompleteStructMember member_accelration_pedal_cmd_enble = TypeObjectUtils::build_complete_struct_member(common_accelration_pedal_cmd_enble, detail_accelration_pedal_cmd_enble);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChassisCommand, member_accelration_pedal_cmd_enble);
        }
        CompleteStructType struct_type_ChassisCommand = TypeObjectUtils::build_complete_struct_type(struct_flags_ChassisCommand, header_ChassisCommand, member_seq_ChassisCommand);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_ChassisCommand, type_name_ChassisCommand.to_string(), type_ids_ChassisCommand))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "control_msgs::msg::ChassisCommand already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace msg

} // namespace control_msgs

