// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ChassisCommandCdrAux.ipp
 * This source file contains some declarations of CDR related functions.
 *
 * This file was generated by the tool fastddsgen (version: 4.2.0).
 */

#ifndef FAST_DDS_GENERATED__CONTROL_MSGS_MSG_CHASSISCOMMANDCDRAUX_IPP
#define FAST_DDS_GENERATED__CONTROL_MSGS_MSG_CHASSISCOMMANDCDRAUX_IPP

#include "ChassisCommandCdrAux.hpp"

#include <fastcdr/Cdr.h>
#include <fastcdr/CdrSizeCalculator.hpp>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

namespace eprosima {
namespace fastcdr {

template<>
eProsima_user_DllExport size_t calculate_serialized_size(
        eprosima::fastcdr::CdrSizeCalculator& calculator,
        const control_msgs::msg::ChassisCommand& data,
        size_t& current_alignment)
{
    using namespace control_msgs::msg;

    static_cast<void>(data);

    eprosima::fastcdr::EncodingAlgorithmFlag previous_encoding = calculator.get_encoding();
    size_t calculated_size {calculator.begin_calculate_type_serialized_size(
                                eprosima::fastcdr::CdrVersion::XCDRv2 == calculator.get_cdr_version() ?
                                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2 :
                                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR,
                                current_alignment)};


        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(0),
                data.ads_function(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(1),
                data.steer_angle_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(2),
                data.steer_wheel_torque_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(3),
                data.steer_vibration_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(4),
                data.long_acceleration_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(5),
                data.long_accelerationjerk_max(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(6),
                data.long_accelerationjerk_min(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(7),
                data.gear_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(8),
                data.aeb_acceleration_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(9),
                data.aeb_acceleration_enable(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(10),
                data.aeb_aba_request(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(11),
                data.aeb_aba_level(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(12),
                data.aeb_jerk_req(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(13),
                data.aeb_jerk_level(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(14),
                data.aeb_prefill_req(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(15),
                data.eba_decel_req(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(16),
                data.aeb_hold_req(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(17),
                data.brake_pedal_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(18),
                data.brake_pedal_cmd_enable(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(19),
                data.accelration_pedal_cmd(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(20),
                data.accelration_pedal_cmd_enble(), current_alignment);


    calculated_size += calculator.end_calculate_type_serialized_size(previous_encoding, current_alignment);

    return calculated_size;
}

template<>
eProsima_user_DllExport void serialize(
        eprosima::fastcdr::Cdr& scdr,
        const control_msgs::msg::ChassisCommand& data)
{
    using namespace control_msgs::msg;

    eprosima::fastcdr::Cdr::state current_state(scdr);
    scdr.begin_serialize_type(current_state,
            eprosima::fastcdr::CdrVersion::XCDRv2 == scdr.get_cdr_version() ?
            eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2 :
            eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR);

    scdr
        << eprosima::fastcdr::MemberId(0) << data.ads_function()
        << eprosima::fastcdr::MemberId(1) << data.steer_angle_cmd()
        << eprosima::fastcdr::MemberId(2) << data.steer_wheel_torque_cmd()
        << eprosima::fastcdr::MemberId(3) << data.steer_vibration_cmd()
        << eprosima::fastcdr::MemberId(4) << data.long_acceleration_cmd()
        << eprosima::fastcdr::MemberId(5) << data.long_accelerationjerk_max()
        << eprosima::fastcdr::MemberId(6) << data.long_accelerationjerk_min()
        << eprosima::fastcdr::MemberId(7) << data.gear_cmd()
        << eprosima::fastcdr::MemberId(8) << data.aeb_acceleration_cmd()
        << eprosima::fastcdr::MemberId(9) << data.aeb_acceleration_enable()
        << eprosima::fastcdr::MemberId(10) << data.aeb_aba_request()
        << eprosima::fastcdr::MemberId(11) << data.aeb_aba_level()
        << eprosima::fastcdr::MemberId(12) << data.aeb_jerk_req()
        << eprosima::fastcdr::MemberId(13) << data.aeb_jerk_level()
        << eprosima::fastcdr::MemberId(14) << data.aeb_prefill_req()
        << eprosima::fastcdr::MemberId(15) << data.eba_decel_req()
        << eprosima::fastcdr::MemberId(16) << data.aeb_hold_req()
        << eprosima::fastcdr::MemberId(17) << data.brake_pedal_cmd()
        << eprosima::fastcdr::MemberId(18) << data.brake_pedal_cmd_enable()
        << eprosima::fastcdr::MemberId(19) << data.accelration_pedal_cmd()
        << eprosima::fastcdr::MemberId(20) << data.accelration_pedal_cmd_enble()
;
    scdr.end_serialize_type(current_state);
}

template<>
eProsima_user_DllExport void deserialize(
        eprosima::fastcdr::Cdr& cdr,
        control_msgs::msg::ChassisCommand& data)
{
    using namespace control_msgs::msg;

    cdr.deserialize_type(eprosima::fastcdr::CdrVersion::XCDRv2 == cdr.get_cdr_version() ?
            eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2 :
            eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR,
            [&data](eprosima::fastcdr::Cdr& dcdr, const eprosima::fastcdr::MemberId& mid) -> bool
            {
                bool ret_value = true;
                switch (mid.id)
                {
                                        case 0:
                                                dcdr >> data.ads_function();
                                            break;

                                        case 1:
                                                dcdr >> data.steer_angle_cmd();
                                            break;

                                        case 2:
                                                dcdr >> data.steer_wheel_torque_cmd();
                                            break;

                                        case 3:
                                                dcdr >> data.steer_vibration_cmd();
                                            break;

                                        case 4:
                                                dcdr >> data.long_acceleration_cmd();
                                            break;

                                        case 5:
                                                dcdr >> data.long_accelerationjerk_max();
                                            break;

                                        case 6:
                                                dcdr >> data.long_accelerationjerk_min();
                                            break;

                                        case 7:
                                                dcdr >> data.gear_cmd();
                                            break;

                                        case 8:
                                                dcdr >> data.aeb_acceleration_cmd();
                                            break;

                                        case 9:
                                                dcdr >> data.aeb_acceleration_enable();
                                            break;

                                        case 10:
                                                dcdr >> data.aeb_aba_request();
                                            break;

                                        case 11:
                                                dcdr >> data.aeb_aba_level();
                                            break;

                                        case 12:
                                                dcdr >> data.aeb_jerk_req();
                                            break;

                                        case 13:
                                                dcdr >> data.aeb_jerk_level();
                                            break;

                                        case 14:
                                                dcdr >> data.aeb_prefill_req();
                                            break;

                                        case 15:
                                                dcdr >> data.eba_decel_req();
                                            break;

                                        case 16:
                                                dcdr >> data.aeb_hold_req();
                                            break;

                                        case 17:
                                                dcdr >> data.brake_pedal_cmd();
                                            break;

                                        case 18:
                                                dcdr >> data.brake_pedal_cmd_enable();
                                            break;

                                        case 19:
                                                dcdr >> data.accelration_pedal_cmd();
                                            break;

                                        case 20:
                                                dcdr >> data.accelration_pedal_cmd_enble();
                                            break;

                    default:
                        ret_value = false;
                        break;
                }
                return ret_value;
            });
}

void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const control_msgs::msg::ChassisCommand& data)
{
    using namespace control_msgs::msg;

    static_cast<void>(scdr);
    static_cast<void>(data);
                        scdr << data.ads_function();

                        scdr << data.steer_angle_cmd();

                        scdr << data.steer_wheel_torque_cmd();

                        scdr << data.steer_vibration_cmd();

                        scdr << data.long_acceleration_cmd();

                        scdr << data.long_accelerationjerk_max();

                        scdr << data.long_accelerationjerk_min();

                        scdr << data.gear_cmd();

                        scdr << data.aeb_acceleration_cmd();

                        scdr << data.aeb_acceleration_enable();

                        scdr << data.aeb_aba_request();

                        scdr << data.aeb_aba_level();

                        scdr << data.aeb_jerk_req();

                        scdr << data.aeb_jerk_level();

                        scdr << data.aeb_prefill_req();

                        scdr << data.eba_decel_req();

                        scdr << data.aeb_hold_req();

                        scdr << data.brake_pedal_cmd();

                        scdr << data.brake_pedal_cmd_enable();

                        scdr << data.accelration_pedal_cmd();

                        scdr << data.accelration_pedal_cmd_enble();

}



} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__CONTROL_MSGS_MSG_CHASSISCOMMANDCDRAUX_IPP

