// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file EgoVehicleCommandTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.2.0).
 */

#include "EgoVehicleCommandTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "EgoVehicleCommand.hpp"

#include "ChassisCommand.hpp"
#include "ACCEgoVehCmdHeader.hpp"
#include "BodyCommand.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace control_msgs {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_EgoVehicleCommand_type_identifier(
        TypeIdentifierPair& type_ids_EgoVehicleCommand)
{

    ReturnCode_t return_code_EgoVehicleCommand {eprosima::fastdds::dds::RETCODE_OK};
    return_code_EgoVehicleCommand =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "control_msgs::msg::dds_::EgoVehicleCommand_", type_ids_EgoVehicleCommand);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_EgoVehicleCommand)
    {
        StructTypeFlag struct_flags_EgoVehicleCommand = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_EgoVehicleCommand = "control_msgs::msg::dds_::EgoVehicleCommand_";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_EgoVehicleCommand;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_EgoVehicleCommand;
        CompleteTypeDetail detail_EgoVehicleCommand = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_EgoVehicleCommand, ann_custom_EgoVehicleCommand, type_name_EgoVehicleCommand.to_string());
        CompleteStructHeader header_EgoVehicleCommand;
        header_EgoVehicleCommand = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_EgoVehicleCommand);
        CompleteStructMemberSeq member_seq_EgoVehicleCommand;
        {
            TypeIdentifierPair type_ids_header;
            ReturnCode_t return_code_header {eprosima::fastdds::dds::RETCODE_OK};
            return_code_header =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "std_msgs::msg::dds_::ACCEgoVehCmdHeader_", type_ids_header);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_header)
            {
                ::std_msgs::msg::register_ACCEgoVehCmdHeader_type_identifier(type_ids_header);
            }
            StructMemberFlag member_flags_header = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_header = 0x00000000;
            bool common_header_ec {false};
            CommonStructMember common_header {TypeObjectUtils::build_common_struct_member(member_id_header, member_flags_header, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_header, common_header_ec))};
            if (!common_header_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure header member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_header = "header";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_header;
            ann_custom_EgoVehicleCommand.reset();
            CompleteMemberDetail detail_header = TypeObjectUtils::build_complete_member_detail(name_header, member_ann_builtin_header, ann_custom_EgoVehicleCommand);
            CompleteStructMember member_header = TypeObjectUtils::build_complete_struct_member(common_header, detail_header);
            TypeObjectUtils::add_complete_struct_member(member_seq_EgoVehicleCommand, member_header);
        }
        {
            TypeIdentifierPair type_ids_chassis_command;
            ReturnCode_t return_code_chassis_command {eprosima::fastdds::dds::RETCODE_OK};
            return_code_chassis_command =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "control_msgs::msg::dds_::ChassisCommand_", type_ids_chassis_command);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_chassis_command)
            {
                ::control_msgs::msg::register_ChassisCommand_type_identifier(type_ids_chassis_command);
            }
            StructMemberFlag member_flags_chassis_command = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_chassis_command = 0x00000001;
            bool common_chassis_command_ec {false};
            CommonStructMember common_chassis_command {TypeObjectUtils::build_common_struct_member(member_id_chassis_command, member_flags_chassis_command, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_chassis_command, common_chassis_command_ec))};
            if (!common_chassis_command_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure chassis_command member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_chassis_command = "chassis_command";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_chassis_command;
            ann_custom_EgoVehicleCommand.reset();
            CompleteMemberDetail detail_chassis_command = TypeObjectUtils::build_complete_member_detail(name_chassis_command, member_ann_builtin_chassis_command, ann_custom_EgoVehicleCommand);
            CompleteStructMember member_chassis_command = TypeObjectUtils::build_complete_struct_member(common_chassis_command, detail_chassis_command);
            TypeObjectUtils::add_complete_struct_member(member_seq_EgoVehicleCommand, member_chassis_command);
        }
        {
            TypeIdentifierPair type_ids_body_command;
            ReturnCode_t return_code_body_command {eprosima::fastdds::dds::RETCODE_OK};
            return_code_body_command =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "control_msgs::msg::dds_::BodyCommand_", type_ids_body_command);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_body_command)
            {
                ::control_msgs::msg::register_BodyCommand_type_identifier(type_ids_body_command);
            }
            StructMemberFlag member_flags_body_command = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_body_command = 0x00000002;
            bool common_body_command_ec {false};
            CommonStructMember common_body_command {TypeObjectUtils::build_common_struct_member(member_id_body_command, member_flags_body_command, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_body_command, common_body_command_ec))};
            if (!common_body_command_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure body_command member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_body_command = "body_command";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_body_command;
            ann_custom_EgoVehicleCommand.reset();
            CompleteMemberDetail detail_body_command = TypeObjectUtils::build_complete_member_detail(name_body_command, member_ann_builtin_body_command, ann_custom_EgoVehicleCommand);
            CompleteStructMember member_body_command = TypeObjectUtils::build_complete_struct_member(common_body_command, detail_body_command);
            TypeObjectUtils::add_complete_struct_member(member_seq_EgoVehicleCommand, member_body_command);
        }
        CompleteStructType struct_type_EgoVehicleCommand = TypeObjectUtils::build_complete_struct_type(struct_flags_EgoVehicleCommand, header_EgoVehicleCommand, member_seq_EgoVehicleCommand);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_EgoVehicleCommand, type_name_EgoVehicleCommand.to_string(), type_ids_EgoVehicleCommand))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "control_msgs::msg::EgoVehicleCommand already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace msg

} // namespace control_msgs

