// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file EgoVehicleCommand.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.2.0).
 */

#ifndef FAST_DDS_GENERATED__CONTROL_MSGS_MSG_EGOVEHICLECOMMAND_HPP
#define FAST_DDS_GENERATED__CONTROL_MSGS_MSG_EGOVEHICLECOMMAND_HPP

#include <cstdint>
#include <utility>
#include "ChassisCommand.hpp"
#include "ACCEgoVehCmdHeader.hpp"
#include "BodyCommand.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(EGOVEHICLECOMMAND_SOURCE)
#define EGOVEHICLECOMMAND_DllAPI __declspec( dllexport )
#else
#define EGOVEHICLECOMMAND_DllAPI __declspec( dllimport )
#endif // EGOVEHICLECOMMAND_SOURCE
#else
#define EGOVEHICLECOMMAND_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define EGOVEHICLECOMMAND_DllAPI
#endif // _WIN32

namespace control_msgs {

namespace msg {

/*!
 * @brief This class represents the structure EgoVehicleCommand defined by the user in the IDL file.
 * @ingroup EgoVehicleCommand
 */
class EgoVehicleCommand
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport EgoVehicleCommand()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~EgoVehicleCommand()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object EgoVehicleCommand that will be copied.
     */
    eProsima_user_DllExport EgoVehicleCommand(
            const EgoVehicleCommand& x)
    {
                    m_header = x.m_header;

                    m_chassis_command = x.m_chassis_command;

                    m_body_command = x.m_body_command;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object EgoVehicleCommand that will be copied.
     */
    eProsima_user_DllExport EgoVehicleCommand(
            EgoVehicleCommand&& x) noexcept
    {
        m_header = std::move(x.m_header);
        m_chassis_command = std::move(x.m_chassis_command);
        m_body_command = std::move(x.m_body_command);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object EgoVehicleCommand that will be copied.
     */
    eProsima_user_DllExport EgoVehicleCommand& operator =(
            const EgoVehicleCommand& x)
    {

                    m_header = x.m_header;

                    m_chassis_command = x.m_chassis_command;

                    m_body_command = x.m_body_command;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object EgoVehicleCommand that will be copied.
     */
    eProsima_user_DllExport EgoVehicleCommand& operator =(
            EgoVehicleCommand&& x) noexcept
    {

        m_header = std::move(x.m_header);
        m_chassis_command = std::move(x.m_chassis_command);
        m_body_command = std::move(x.m_body_command);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x EgoVehicleCommand object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const EgoVehicleCommand& x) const
    {
        return (m_header == x.m_header &&
           m_chassis_command == x.m_chassis_command &&
           m_body_command == x.m_body_command);
    }

    /*!
     * @brief Comparison operator.
     * @param x EgoVehicleCommand object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const EgoVehicleCommand& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(
            const std_msgs::msg::ACCEgoVehCmdHeader& _header)
    {
        m_header = _header;
    }

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(
            std_msgs::msg::ACCEgoVehCmdHeader&& _header)
    {
        m_header = std::move(_header);
    }

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const std_msgs::msg::ACCEgoVehCmdHeader& header() const
    {
        return m_header;
    }

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport std_msgs::msg::ACCEgoVehCmdHeader& header()
    {
        return m_header;
    }


    /*!
     * @brief This function copies the value in member chassis_command
     * @param _chassis_command New value to be copied in member chassis_command
     */
    eProsima_user_DllExport void chassis_command(
            const ChassisCommand& _chassis_command)
    {
        m_chassis_command = _chassis_command;
    }

    /*!
     * @brief This function moves the value in member chassis_command
     * @param _chassis_command New value to be moved in member chassis_command
     */
    eProsima_user_DllExport void chassis_command(
            ChassisCommand&& _chassis_command)
    {
        m_chassis_command = std::move(_chassis_command);
    }

    /*!
     * @brief This function returns a constant reference to member chassis_command
     * @return Constant reference to member chassis_command
     */
    eProsima_user_DllExport const ChassisCommand& chassis_command() const
    {
        return m_chassis_command;
    }

    /*!
     * @brief This function returns a reference to member chassis_command
     * @return Reference to member chassis_command
     */
    eProsima_user_DllExport ChassisCommand& chassis_command()
    {
        return m_chassis_command;
    }


    /*!
     * @brief This function copies the value in member body_command
     * @param _body_command New value to be copied in member body_command
     */
    eProsima_user_DllExport void body_command(
            const BodyCommand& _body_command)
    {
        m_body_command = _body_command;
    }

    /*!
     * @brief This function moves the value in member body_command
     * @param _body_command New value to be moved in member body_command
     */
    eProsima_user_DllExport void body_command(
            BodyCommand&& _body_command)
    {
        m_body_command = std::move(_body_command);
    }

    /*!
     * @brief This function returns a constant reference to member body_command
     * @return Constant reference to member body_command
     */
    eProsima_user_DllExport const BodyCommand& body_command() const
    {
        return m_body_command;
    }

    /*!
     * @brief This function returns a reference to member body_command
     * @return Reference to member body_command
     */
    eProsima_user_DllExport BodyCommand& body_command()
    {
        return m_body_command;
    }



private:

    std_msgs::msg::ACCEgoVehCmdHeader m_header;
    ChassisCommand m_chassis_command;
    BodyCommand m_body_command;

};

} // namespace msg

} // namespace control_msgs

#endif // _FAST_DDS_GENERATED_CONTROL_MSGS_MSG_EGOVEHICLECOMMAND_HPP_


