// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SystemMonitor.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__SOC_MONITOR_MSG_SYSTEMMONITOR_HPP
#define FAST_DDS_GENERATED__SOC_MONITOR_MSG_SYSTEMMONITOR_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(SYSTEMMONITOR_SOURCE)
#define SYSTEMMONITOR_DllAPI __declspec( dllexport )
#else
#define SYSTEMMONITOR_DllAPI __declspec( dllimport )
#endif // SYSTEMMONITOR_SOURCE
#else
#define SYSTEMMONITOR_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define SYSTEMMONITOR_DllAPI
#endif // _WIN32

namespace soc_monitor {

namespace msg {

/*!
 * @brief This class represents the structure ThermalZone defined by the user in the IDL file.
 * @ingroup SystemMonitor
 */
class ThermalZone
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ThermalZone()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ThermalZone()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ThermalZone that will be copied.
     */
    eProsima_user_DllExport ThermalZone(
            const ThermalZone& x)
    {
                    m_name = x.m_name;

                    m_temperature = x.m_temperature;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ThermalZone that will be copied.
     */
    eProsima_user_DllExport ThermalZone(
            ThermalZone&& x) noexcept
    {
        m_name = std::move(x.m_name);
        m_temperature = x.m_temperature;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ThermalZone that will be copied.
     */
    eProsima_user_DllExport ThermalZone& operator =(
            const ThermalZone& x)
    {

                    m_name = x.m_name;

                    m_temperature = x.m_temperature;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ThermalZone that will be copied.
     */
    eProsima_user_DllExport ThermalZone& operator =(
            ThermalZone&& x) noexcept
    {

        m_name = std::move(x.m_name);
        m_temperature = x.m_temperature;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x ThermalZone object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ThermalZone& x) const
    {
        return (m_name == x.m_name &&
           m_temperature == x.m_temperature);
    }

    /*!
     * @brief Comparison operator.
     * @param x ThermalZone object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ThermalZone& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    eProsima_user_DllExport void name(
            const std::string& _name)
    {
        m_name = _name;
    }

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    eProsima_user_DllExport void name(
            std::string&& _name)
    {
        m_name = std::move(_name);
    }

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    eProsima_user_DllExport const std::string& name() const
    {
        return m_name;
    }

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    eProsima_user_DllExport std::string& name()
    {
        return m_name;
    }


    /*!
     * @brief This function sets a value in member temperature
     * @param _temperature New value for member temperature
     */
    eProsima_user_DllExport void temperature(
            float _temperature)
    {
        m_temperature = _temperature;
    }

    /*!
     * @brief This function returns the value of member temperature
     * @return Value of member temperature
     */
    eProsima_user_DllExport float temperature() const
    {
        return m_temperature;
    }

    /*!
     * @brief This function returns a reference to member temperature
     * @return Reference to member temperature
     */
    eProsima_user_DllExport float& temperature()
    {
        return m_temperature;
    }



private:

    std::string m_name;
    float m_temperature{0.0};

};
/*!
 * @brief This class represents the structure SystemMonitorMsg defined by the user in the IDL file.
 * @ingroup SystemMonitor
 */
class SystemMonitorMsg
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SystemMonitorMsg()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SystemMonitorMsg()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SystemMonitorMsg that will be copied.
     */
    eProsima_user_DllExport SystemMonitorMsg(
            const SystemMonitorMsg& x)
    {
                    m_thermals = x.m_thermals;

                    m_cpu_core_loads = x.m_cpu_core_loads;

                    m_avg_cpu_load = x.m_avg_cpu_load;

                    m_max_cpu_load = x.m_max_cpu_load;

                    m_ram_usage = x.m_ram_usage;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SystemMonitorMsg that will be copied.
     */
    eProsima_user_DllExport SystemMonitorMsg(
            SystemMonitorMsg&& x) noexcept
    {
        m_thermals = std::move(x.m_thermals);
        m_cpu_core_loads = std::move(x.m_cpu_core_loads);
        m_avg_cpu_load = x.m_avg_cpu_load;
        m_max_cpu_load = x.m_max_cpu_load;
        m_ram_usage = x.m_ram_usage;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SystemMonitorMsg that will be copied.
     */
    eProsima_user_DllExport SystemMonitorMsg& operator =(
            const SystemMonitorMsg& x)
    {

                    m_thermals = x.m_thermals;

                    m_cpu_core_loads = x.m_cpu_core_loads;

                    m_avg_cpu_load = x.m_avg_cpu_load;

                    m_max_cpu_load = x.m_max_cpu_load;

                    m_ram_usage = x.m_ram_usage;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SystemMonitorMsg that will be copied.
     */
    eProsima_user_DllExport SystemMonitorMsg& operator =(
            SystemMonitorMsg&& x) noexcept
    {

        m_thermals = std::move(x.m_thermals);
        m_cpu_core_loads = std::move(x.m_cpu_core_loads);
        m_avg_cpu_load = x.m_avg_cpu_load;
        m_max_cpu_load = x.m_max_cpu_load;
        m_ram_usage = x.m_ram_usage;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x SystemMonitorMsg object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SystemMonitorMsg& x) const
    {
        return (m_thermals == x.m_thermals &&
           m_cpu_core_loads == x.m_cpu_core_loads &&
           m_avg_cpu_load == x.m_avg_cpu_load &&
           m_max_cpu_load == x.m_max_cpu_load &&
           m_ram_usage == x.m_ram_usage);
    }

    /*!
     * @brief Comparison operator.
     * @param x SystemMonitorMsg object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SystemMonitorMsg& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member thermals
     * @param _thermals New value to be copied in member thermals
     */
    eProsima_user_DllExport void thermals(
            const std::vector<ThermalZone>& _thermals)
    {
        m_thermals = _thermals;
    }

    /*!
     * @brief This function moves the value in member thermals
     * @param _thermals New value to be moved in member thermals
     */
    eProsima_user_DllExport void thermals(
            std::vector<ThermalZone>&& _thermals)
    {
        m_thermals = std::move(_thermals);
    }

    /*!
     * @brief This function returns a constant reference to member thermals
     * @return Constant reference to member thermals
     */
    eProsima_user_DllExport const std::vector<ThermalZone>& thermals() const
    {
        return m_thermals;
    }

    /*!
     * @brief This function returns a reference to member thermals
     * @return Reference to member thermals
     */
    eProsima_user_DllExport std::vector<ThermalZone>& thermals()
    {
        return m_thermals;
    }


    /*!
     * @brief This function copies the value in member cpu_core_loads
     * @param _cpu_core_loads New value to be copied in member cpu_core_loads
     */
    eProsima_user_DllExport void cpu_core_loads(
            const std::vector<float>& _cpu_core_loads)
    {
        m_cpu_core_loads = _cpu_core_loads;
    }

    /*!
     * @brief This function moves the value in member cpu_core_loads
     * @param _cpu_core_loads New value to be moved in member cpu_core_loads
     */
    eProsima_user_DllExport void cpu_core_loads(
            std::vector<float>&& _cpu_core_loads)
    {
        m_cpu_core_loads = std::move(_cpu_core_loads);
    }

    /*!
     * @brief This function returns a constant reference to member cpu_core_loads
     * @return Constant reference to member cpu_core_loads
     */
    eProsima_user_DllExport const std::vector<float>& cpu_core_loads() const
    {
        return m_cpu_core_loads;
    }

    /*!
     * @brief This function returns a reference to member cpu_core_loads
     * @return Reference to member cpu_core_loads
     */
    eProsima_user_DllExport std::vector<float>& cpu_core_loads()
    {
        return m_cpu_core_loads;
    }


    /*!
     * @brief This function sets a value in member avg_cpu_load
     * @param _avg_cpu_load New value for member avg_cpu_load
     */
    eProsima_user_DllExport void avg_cpu_load(
            float _avg_cpu_load)
    {
        m_avg_cpu_load = _avg_cpu_load;
    }

    /*!
     * @brief This function returns the value of member avg_cpu_load
     * @return Value of member avg_cpu_load
     */
    eProsima_user_DllExport float avg_cpu_load() const
    {
        return m_avg_cpu_load;
    }

    /*!
     * @brief This function returns a reference to member avg_cpu_load
     * @return Reference to member avg_cpu_load
     */
    eProsima_user_DllExport float& avg_cpu_load()
    {
        return m_avg_cpu_load;
    }


    /*!
     * @brief This function sets a value in member max_cpu_load
     * @param _max_cpu_load New value for member max_cpu_load
     */
    eProsima_user_DllExport void max_cpu_load(
            float _max_cpu_load)
    {
        m_max_cpu_load = _max_cpu_load;
    }

    /*!
     * @brief This function returns the value of member max_cpu_load
     * @return Value of member max_cpu_load
     */
    eProsima_user_DllExport float max_cpu_load() const
    {
        return m_max_cpu_load;
    }

    /*!
     * @brief This function returns a reference to member max_cpu_load
     * @return Reference to member max_cpu_load
     */
    eProsima_user_DllExport float& max_cpu_load()
    {
        return m_max_cpu_load;
    }


    /*!
     * @brief This function sets a value in member ram_usage
     * @param _ram_usage New value for member ram_usage
     */
    eProsima_user_DllExport void ram_usage(
            float _ram_usage)
    {
        m_ram_usage = _ram_usage;
    }

    /*!
     * @brief This function returns the value of member ram_usage
     * @return Value of member ram_usage
     */
    eProsima_user_DllExport float ram_usage() const
    {
        return m_ram_usage;
    }

    /*!
     * @brief This function returns a reference to member ram_usage
     * @return Reference to member ram_usage
     */
    eProsima_user_DllExport float& ram_usage()
    {
        return m_ram_usage;
    }



private:

    std::vector<ThermalZone> m_thermals;
    std::vector<float> m_cpu_core_loads;
    float m_avg_cpu_load{0.0};
    float m_max_cpu_load{0.0};
    float m_ram_usage{0.0};

};

} // namespace msg

} // namespace soc_monitor

#endif // _FAST_DDS_GENERATED_SOC_MONITOR_MSG_SYSTEMMONITOR_HPP_


