// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SystemMonitorTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "SystemMonitorTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "SystemMonitor.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace soc_monitor {
namespace msg {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_ThermalZone_type_identifier(
        TypeIdentifierPair& type_ids_ThermalZone)
{

    ReturnCode_t return_code_ThermalZone {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ThermalZone =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "soc_monitor::msg::ThermalZone", type_ids_ThermalZone);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ThermalZone)
    {
        StructTypeFlag struct_flags_ThermalZone = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_ThermalZone = "soc_monitor::msg::ThermalZone";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ThermalZone;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ThermalZone;
        CompleteTypeDetail detail_ThermalZone = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ThermalZone, ann_custom_ThermalZone, type_name_ThermalZone.to_string());
        CompleteStructHeader header_ThermalZone;
        header_ThermalZone = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_ThermalZone);
        CompleteStructMemberSeq member_seq_ThermalZone;
        {
            TypeIdentifierPair type_ids_name;
            ReturnCode_t return_code_name {eprosima::fastdds::dds::RETCODE_OK};
            return_code_name =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_name);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_name)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_name))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_name = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_name = 0x00000000;
            bool common_name_ec {false};
            CommonStructMember common_name {TypeObjectUtils::build_common_struct_member(member_id_name, member_flags_name, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_name, common_name_ec))};
            if (!common_name_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure name member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_name = "name";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_name;
            ann_custom_ThermalZone.reset();
            CompleteMemberDetail detail_name = TypeObjectUtils::build_complete_member_detail(name_name, member_ann_builtin_name, ann_custom_ThermalZone);
            CompleteStructMember member_name = TypeObjectUtils::build_complete_struct_member(common_name, detail_name);
            TypeObjectUtils::add_complete_struct_member(member_seq_ThermalZone, member_name);
        }
        {
            TypeIdentifierPair type_ids_temperature;
            ReturnCode_t return_code_temperature {eprosima::fastdds::dds::RETCODE_OK};
            return_code_temperature =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_temperature);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_temperature)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "temperature Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_temperature = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_temperature = 0x00000001;
            bool common_temperature_ec {false};
            CommonStructMember common_temperature {TypeObjectUtils::build_common_struct_member(member_id_temperature, member_flags_temperature, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_temperature, common_temperature_ec))};
            if (!common_temperature_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure temperature member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_temperature = "temperature";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_temperature;
            ann_custom_ThermalZone.reset();
            CompleteMemberDetail detail_temperature = TypeObjectUtils::build_complete_member_detail(name_temperature, member_ann_builtin_temperature, ann_custom_ThermalZone);
            CompleteStructMember member_temperature = TypeObjectUtils::build_complete_struct_member(common_temperature, detail_temperature);
            TypeObjectUtils::add_complete_struct_member(member_seq_ThermalZone, member_temperature);
        }
        CompleteStructType struct_type_ThermalZone = TypeObjectUtils::build_complete_struct_type(struct_flags_ThermalZone, header_ThermalZone, member_seq_ThermalZone);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_ThermalZone, type_name_ThermalZone.to_string(), type_ids_ThermalZone))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "soc_monitor::msg::ThermalZone already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_SystemMonitorMsg_type_identifier(
        TypeIdentifierPair& type_ids_SystemMonitorMsg)
{

    ReturnCode_t return_code_SystemMonitorMsg {eprosima::fastdds::dds::RETCODE_OK};
    return_code_SystemMonitorMsg =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "soc_monitor::msg::SystemMonitorMsg", type_ids_SystemMonitorMsg);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_SystemMonitorMsg)
    {
        StructTypeFlag struct_flags_SystemMonitorMsg = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_SystemMonitorMsg = "soc_monitor::msg::SystemMonitorMsg";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_SystemMonitorMsg;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_SystemMonitorMsg;
        CompleteTypeDetail detail_SystemMonitorMsg = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_SystemMonitorMsg, ann_custom_SystemMonitorMsg, type_name_SystemMonitorMsg.to_string());
        CompleteStructHeader header_SystemMonitorMsg;
        header_SystemMonitorMsg = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_SystemMonitorMsg);
        CompleteStructMemberSeq member_seq_SystemMonitorMsg;
        {
            TypeIdentifierPair type_ids_thermals;
            ReturnCode_t return_code_thermals {eprosima::fastdds::dds::RETCODE_OK};
            return_code_thermals =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded", type_ids_thermals);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_thermals)
            {
                return_code_thermals =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "soc_monitor::msg::ThermalZone", type_ids_thermals);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_thermals)
                {
                    soc_monitor::msg::register_ThermalZone_type_identifier(type_ids_thermals);
                }
                bool element_identifier_anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_thermals, element_identifier_anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded_ec))};
                if (!element_identifier_anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded = EK_COMPLETE;
                if (TK_NONE == type_ids_thermals.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded = 0;
                PlainCollectionHeader header_anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded, element_flags_anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded);
                {
                    SBound bound = 0;
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded", type_ids_thermals))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_soc_monitor_msg_ThermalZone_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_thermals = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_thermals = 0x00000000;
            bool common_thermals_ec {false};
            CommonStructMember common_thermals {TypeObjectUtils::build_common_struct_member(member_id_thermals, member_flags_thermals, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_thermals, common_thermals_ec))};
            if (!common_thermals_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure thermals member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_thermals = "thermals";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_thermals;
            ann_custom_SystemMonitorMsg.reset();
            CompleteMemberDetail detail_thermals = TypeObjectUtils::build_complete_member_detail(name_thermals, member_ann_builtin_thermals, ann_custom_SystemMonitorMsg);
            CompleteStructMember member_thermals = TypeObjectUtils::build_complete_struct_member(common_thermals, detail_thermals);
            TypeObjectUtils::add_complete_struct_member(member_seq_SystemMonitorMsg, member_thermals);
        }
        {
            TypeIdentifierPair type_ids_cpu_core_loads;
            ReturnCode_t return_code_cpu_core_loads {eprosima::fastdds::dds::RETCODE_OK};
            return_code_cpu_core_loads =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_float_unbounded", type_ids_cpu_core_loads);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_cpu_core_loads)
            {
                return_code_cpu_core_loads =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_float", type_ids_cpu_core_loads);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_cpu_core_loads)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Sequence element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_sequence_float_unbounded_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_float_unbounded {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_cpu_core_loads, element_identifier_anonymous_sequence_float_unbounded_ec))};
                if (!element_identifier_anonymous_sequence_float_unbounded_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_float_unbounded = EK_COMPLETE;
                if (TK_NONE == type_ids_cpu_core_loads.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_float_unbounded = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_float_unbounded = 0;
                PlainCollectionHeader header_anonymous_sequence_float_unbounded = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_float_unbounded, element_flags_anonymous_sequence_float_unbounded);
                {
                    SBound bound = 0;
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_float_unbounded, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_float_unbounded));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_float_unbounded", type_ids_cpu_core_loads))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_float_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_cpu_core_loads = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_cpu_core_loads = 0x00000001;
            bool common_cpu_core_loads_ec {false};
            CommonStructMember common_cpu_core_loads {TypeObjectUtils::build_common_struct_member(member_id_cpu_core_loads, member_flags_cpu_core_loads, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_cpu_core_loads, common_cpu_core_loads_ec))};
            if (!common_cpu_core_loads_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure cpu_core_loads member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_cpu_core_loads = "cpu_core_loads";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_cpu_core_loads;
            ann_custom_SystemMonitorMsg.reset();
            CompleteMemberDetail detail_cpu_core_loads = TypeObjectUtils::build_complete_member_detail(name_cpu_core_loads, member_ann_builtin_cpu_core_loads, ann_custom_SystemMonitorMsg);
            CompleteStructMember member_cpu_core_loads = TypeObjectUtils::build_complete_struct_member(common_cpu_core_loads, detail_cpu_core_loads);
            TypeObjectUtils::add_complete_struct_member(member_seq_SystemMonitorMsg, member_cpu_core_loads);
        }
        {
            TypeIdentifierPair type_ids_avg_cpu_load;
            ReturnCode_t return_code_avg_cpu_load {eprosima::fastdds::dds::RETCODE_OK};
            return_code_avg_cpu_load =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_avg_cpu_load);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_avg_cpu_load)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "avg_cpu_load Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_avg_cpu_load = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_avg_cpu_load = 0x00000002;
            bool common_avg_cpu_load_ec {false};
            CommonStructMember common_avg_cpu_load {TypeObjectUtils::build_common_struct_member(member_id_avg_cpu_load, member_flags_avg_cpu_load, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_avg_cpu_load, common_avg_cpu_load_ec))};
            if (!common_avg_cpu_load_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure avg_cpu_load member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_avg_cpu_load = "avg_cpu_load";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_avg_cpu_load;
            ann_custom_SystemMonitorMsg.reset();
            CompleteMemberDetail detail_avg_cpu_load = TypeObjectUtils::build_complete_member_detail(name_avg_cpu_load, member_ann_builtin_avg_cpu_load, ann_custom_SystemMonitorMsg);
            CompleteStructMember member_avg_cpu_load = TypeObjectUtils::build_complete_struct_member(common_avg_cpu_load, detail_avg_cpu_load);
            TypeObjectUtils::add_complete_struct_member(member_seq_SystemMonitorMsg, member_avg_cpu_load);
        }
        {
            TypeIdentifierPair type_ids_max_cpu_load;
            ReturnCode_t return_code_max_cpu_load {eprosima::fastdds::dds::RETCODE_OK};
            return_code_max_cpu_load =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_max_cpu_load);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_max_cpu_load)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "max_cpu_load Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_max_cpu_load = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_max_cpu_load = 0x00000003;
            bool common_max_cpu_load_ec {false};
            CommonStructMember common_max_cpu_load {TypeObjectUtils::build_common_struct_member(member_id_max_cpu_load, member_flags_max_cpu_load, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_max_cpu_load, common_max_cpu_load_ec))};
            if (!common_max_cpu_load_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure max_cpu_load member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_max_cpu_load = "max_cpu_load";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_max_cpu_load;
            ann_custom_SystemMonitorMsg.reset();
            CompleteMemberDetail detail_max_cpu_load = TypeObjectUtils::build_complete_member_detail(name_max_cpu_load, member_ann_builtin_max_cpu_load, ann_custom_SystemMonitorMsg);
            CompleteStructMember member_max_cpu_load = TypeObjectUtils::build_complete_struct_member(common_max_cpu_load, detail_max_cpu_load);
            TypeObjectUtils::add_complete_struct_member(member_seq_SystemMonitorMsg, member_max_cpu_load);
        }
        {
            TypeIdentifierPair type_ids_ram_usage;
            ReturnCode_t return_code_ram_usage {eprosima::fastdds::dds::RETCODE_OK};
            return_code_ram_usage =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_ram_usage);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ram_usage)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "ram_usage Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_ram_usage = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_ram_usage = 0x00000004;
            bool common_ram_usage_ec {false};
            CommonStructMember common_ram_usage {TypeObjectUtils::build_common_struct_member(member_id_ram_usage, member_flags_ram_usage, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ram_usage, common_ram_usage_ec))};
            if (!common_ram_usage_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure ram_usage member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_ram_usage = "ram_usage";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ram_usage;
            ann_custom_SystemMonitorMsg.reset();
            CompleteMemberDetail detail_ram_usage = TypeObjectUtils::build_complete_member_detail(name_ram_usage, member_ann_builtin_ram_usage, ann_custom_SystemMonitorMsg);
            CompleteStructMember member_ram_usage = TypeObjectUtils::build_complete_struct_member(common_ram_usage, detail_ram_usage);
            TypeObjectUtils::add_complete_struct_member(member_seq_SystemMonitorMsg, member_ram_usage);
        }
        CompleteStructType struct_type_SystemMonitorMsg = TypeObjectUtils::build_complete_struct_type(struct_flags_SystemMonitorMsg, header_SystemMonitorMsg, member_seq_SystemMonitorMsg);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_SystemMonitorMsg, type_name_SystemMonitorMsg.to_string(), type_ids_SystemMonitorMsg))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "soc_monitor::msg::SystemMonitorMsg already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace msg

} // namespace soc_monitor

